### ISSUE TITLE
Ossec conf generator does not correctly combine configuration for syscollector in integration test

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-qa#1045]
A member of the core team told us that after applying the following custom configuration for syscollector in an integration test:

```
- tags:
  - TAG
  apply_to_modules:
  - test_general_configuration_enabled
  sections:
  - section: wodle
    attributes:
      - name: 'syscollector'
    elements:
      - disabled:
          value: yes
```

the resulting configuration appears to be as follows

```
  <wodle name="syscollector">
    <disabled>True</disabled>
  </wodle>

  <wodle name="syscollector">
    <disabled>no</disabled>
    <interval>1h</interval>
    <scan_on_start>yes</scan_on_start>
    <hardware>yes</hardware>
    <os>yes</os>
    <network>yes</network>
    <packages>yes</packages>
    <ports all="no">yes</ports>
    <processes>yes</processes>
  </wodle>   
```

When in fact it should be mixed and unified, giving preference to the configuration specified in the test.

It is requested to investigate this case and solve it.

Regards.
