### ISSUE TITLE
Test active response problems with the yaml configuration

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh-qa#1060]
Hi team,  In the **test_active_response/test_execd**
while testing active-response, I noticed that there is a small problem in the yaml that generates the active-response configuration:

```
- tags:
  - all
  apply_to_modules:
  - test_execd_restart
  - test_execd_firewall_drop
  - conftest
  sections:
  - section: client
    elements:
    - notify_time:
        value: 10
    - time-reconnect:
        value: 60
    - auto_restart:
        value: 'yes'
    - crypto_method:
        value: 'aes'
    - server:
        elements:
        - address:
            value: SERVER_ADDRESS
        - port:
            value: REMOTED_PORT
        - protocol:
            value: PROTOCOL
  - section: active-response
    elements:
    - disabled:
        value: 'no'

```

The active-response section has a line that duplicates config, which causes active-response to be disabled in the tests. I have tested the master branch of wazuh and the test result is failed, because active-response is disabled:
![image](https://user-images.githubusercontent.com/60003131/107957507-ffae5e00-6fa0-11eb-9778-5abb5b072d69.png)

That causes:
`2021/02/12 09:02:30 wazuh-execd: INFO: (1350): Active response disabled.`

I've tested in jenkins, with this difference in the yaml:
![image](https://user-images.githubusercontent.com/60003131/107957648-2cfb0c00-6fa1-11eb-8426-23694ec617bd.png)

Result without fix (failed):
[agent_ubuntu_html_report_test_integration_B1281_20210215124623.zip](https://github.com/wazuh/wazuh-qa/files/5982032/agent_ubuntu_html_report_test_integration_B1281_20210215124623.zip)
[agent_windows_html_report_test_integration_B1281_20210215124623.zip](https://github.com/wazuh/wazuh-qa/files/5982033/agent_windows_html_report_test_integration_B1281_20210215124623.zip)
[agent_centos_html_report_test_integration_B1281_20210215124623.zip](https://github.com/wazuh/wazuh-qa/files/5982034/agent_centos_html_report_test_integration_B1281_20210215124623.zip)

Results with fix (passed):
[agent_windows_html_report_test_integration_B1280_20210215122015.zip](https://github.com/wazuh/wazuh-qa/files/5982038/agent_windows_html_report_test_integration_B1280_20210215122015.zip)
[agent_ubuntu_html_report_test_integration_B1280_20210215122015.zip](https://github.com/wazuh/wazuh-qa/files/5982039/agent_ubuntu_html_report_test_integration_B1280_20210215122015.zip)
[agent_centos_html_report_test_integration_B1280_20210215122015.zip](https://github.com/wazuh/wazuh-qa/files/5982040/agent_centos_html_report_test_integration_B1280_20210215122015.zip)
