### ISSUE TITLE
Create Ansible module to define and run remote deployments and tasks in QACTL

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh-qa#1596]
## Description

This issue is intended to generate an ansible module of the Wazuh provisioning script for when it is necessary to do it remotely. This way we can abstract to generate a list of tasks to be executed.
To make the design more consistent for the future, this module should be abstract enough to be able to perform other functions remotely.

![image](https://user-images.githubusercontent.com/60003131/125609262-caef4e2c-6a6d-49ee-ba57-13a30539a9b9.png)
## To do list

- [x] AnsibleRunner
  - [x] AnsibleOutput
  - [x] AnsiblePlaybook
    - [x] AnsibleTask
    - [x] AnsibleRole
  - [x] AnsibleInventory
    - [x] AnsibleInstance

**Comment by jotacarma90** [comment]
I'm working on the AnsiblePlaybook, AnsibleRole and AnsibleTask classes. Here is the first commit with the actual state of the code:
https://github.com/wazuh/wazuh-qa/commit/4b588e91e9b36742031e71c0f3b4994a989fd541


I have been thinking about the role and task objects, finally, for a first flow, I have created the task class defining it as a task name and a dictionary with the commands of which it is composed.
Consequently, I created the role class by grouping a list of tasks and obtaining a string with all the tasks needed by the playbook.
The Playbook class still needs some work, but it consists of generating a playbook with all the host groups that have been configured, adding a role generated with a list of tasks.

**Comment by JoseAntonioMHerrera** [comment]
Working on the Ansible inventory generation ([AnsibleInventory](https://github.com/wazuh/wazuh-qa/commit/ef0ee36a89b1824191c71d242621f966e27e0b4e), [AnsibleInstance](https://github.com/wazuh/wazuh-qa/commit/429b8314b4172c4de077c2d99e3e7bcb1d2bbdc7), [qa_provisioning.py](https://github.com/wazuh/wazuh-qa/commit/671e664e305db09e929e64be81da177d4a718e3d)), the current workflow allows to read from a .yml file where the infraestructure is defined and generate the analogous ansible inventory. The current .yml syntax is the following:

```
hosts:
    host1:
        host_info:
            connection_method: ssh
            host: 192.168.16.2
            user: vagrant
            password: vagrant
            connection_port: 22
            group: managers
            local_private_key_file_path: ~/.ssh/private
            ansible_python_interpreter: /usr/lib/python3.2
            host_vars:
                var1: value1
                var2: value2

        wazuh_deployment:
            wazuh_installation:
                type: sources
                target: managers
                manager_ip: 192.168.16.2
                wazuh_branch: 7592-syscheck-field-renaming

            package_info:
                type: null
                version: null
                system: null
                revision: null
                architecture: null
                s3_repository: null
                local_package_path: null
                remote_package_path: null

        qa_framework:
            wazuh_qa_branch: 845-added-test-for-something
            qa_workdir: /home/vagrant/qa/

    host2:
       ...

    host3:
      ...

groups:
    managers:
        group_vars:
            var1: manager_var_1
            var2: manager_var_2
    agents:
        group_vars:
            var1: agent_var_1
            var2: agent_var_2
```
