### ISSUE TITLE
Create common tcases structure

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#1933]
### Description

Currently, the definition of the cases of each test is not consistent in the repository.  According to new standards, tcases should be defined in a yaml external file, so, every test should be refactored in order to fulfil this structure. This is necessary due to:

- Standardized the structure of our tests
- Improve legiability

### To do

In order to finish this issue, the following tasks need to be done:
- [ ] Create a test case template. This will be a `yaml` restructure used by all tests in the repository. It should have a description, name, id, arguments, etc.
```
---
- 
  name:
  description: 
  id: port-1154
  test_case:
      - port: 1154
----

  name:
  description: 
  id: port-1153
  test_case:
    - port: 1153
```

- [ ] Create tools (fixtures/function) to load these cases, if it is needed
