### ISSUE TITLE
Design new module to launch tasks in a generalized way in `qa-ctl`

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-qa#2239]
We want to add a new module to `qa-ctl` to be able to launch custom tasks remotely.

To do so, we propose to make use of the ansible module, specifying in this module one or a set of playbooks to be launched in the indicated hosts.

This new module should be reflected in the configuration file, adding for example a new section called `tasks`.

```
deployment:
    ...

provisioning:
    ...

tasks:
    task_1:
        ...

tests:
    ...

config:
    ...
```

An efficient design of this new module is requested for its subsequent implementation.

**Comment by jmv74211** [comment]
In order to be able to launch remote tasks from the `qa-ctl` tool, the `ansible` module has been considered. Basically, this functionality can be designed based on the execution of playbooks in the indicated hosts. To do this, first of all you would have to specify in the `qa-ctl` configuration file the connection information to the hosts and the playbooks containing the tasks to be executed.

## Configuration block of the tasks module

It is proposed to add the following configuration block:

```
tasks:
    task_1:
        host_info:
            ansible_connection: ssh
            ansible_user: vagrant
            ansible_password: vagrant
            ansible_port: 22
            ansible_python_interpreter: /usr/bin/python3
            installation_files_path: /tmp
            host: 10.150.50.2

        playbooks:
            - local_path: 
              remote_url:
              extra_vars:
                  var_1: value
                  var_2: value
              env_vars:
                  var_1: value
                  var_2: value

            - local_path: 
              remote_url:
              extra_vars:
                  ...
              env_vars:
                  ...
    task_2:
        host_info:
            ...
        playbooks:
            ...            
```


`tasks` will be the new configuration block to identify the tasks to be executed. In this module we can specify all the tasks we want to be performed (`task_1`...`task_n`). 

The task is associated to a node, where we specify the connection information in `host_info`. 

All actions to be performed are defined in ansible-playbooks represented by the `playbooks` block. This block contains a list of playbooks to execute.

Each element of the `playbooks` block must contain one of the following elements:

- `local_path`: Used to specify a local path where the playbook to run is located.
- `remote_url`: Used to specify a URL where the playbook to use is located. This playbook will be downloaded and executed by `qa-ctl`.

In addition, you can optionally specify extra `extra_vars` or environment variables (`env_vars`) used in the execution of the playbook.

## Process flow for the task module

First, `qa-ctl` will read the configuration file and process the information blocks. In case the `tasks` module exists, it will create the corresponding `QATasks` object that will parse all the information, building the necessary objects to manage the ansible inventories and then execute the playbooks with their respective inventories
![Untitled Diagram drawio](https://user-images.githubusercontent.com/23462183/142855753-e2178924-7c13-45d7-9184-49acdb7c30c1.png)
.
