### ISSUE TITLE
Update API configuration integration tests

### ISSUE THREAD

**Issue by vicferpoy** [wazuh/wazuh-qa#2365]
As part of https://github.com/wazuh/wazuh/issues/11414, the API integration tests related to its configuration options must be updated:

1. **API log path** is no longer configurable. It was deprecated: https://github.com/wazuh/wazuh-qa/tree/master/tests/integration/test_api/test_config/test_logs

2. **HTTPS configuration files** will only allow file names instead of relative paths: https://github.com/wazuh/wazuh-qa/tree/master/tests/integration/test_api/test_config/test_https

Before:

```yaml
 logs:
  path: "logs/api.log"

 https:
  key: "api/configuration/ssl/server.key"
  cert: "api/configuration/ssl/server.crt"
  ca: "api/configuration/ssl/ca.crt"

```

After:

```yaml
 https:
  key: "server.key"
  cert: "server.crt"
  ca: "ca.crt"
```

The previous default values for both options will be the standard now.
