### ISSUE TITLE
System test: New design research

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#2440]
### Description

This issue aims to report on the current status of system testing and discuss the new design. Some approaches will be proposed.

###  TODO
- [x] Research current design: https://github.com/wazuh/wazuh-qa/issues/2440#issuecomment-1094923781
- [x] Brainstormong ad proposed new system test designs
- [x] Meeting and selection of new model

**Comment by roronoasins** [comment]
# Current design

## Deployment

Currently, to run the system tests we deploy docker containers with ansible connection. You can deploy and destroy a few of environment types.

<details>

<summary>Deployment sample</summary>
</br>

Navigating to the desired environment path, you can deploy and provision it by running:
```
ansible-playbook -i inventory.yml playbook.yml --extra-vars='{"wazuh_branch":"master"}'
```
For `basic_cluster` we need to specify also the `qa_branch`:
```
ansible-playbook -i inventory.yml playbook.yml --extra-vars='{"wazuh_branch":"master", "wazuh_qa_branch":"master"}'`
```

</details>

<details>

<summary>Destroy sample</summary>
</br>

To destroy the environment, you must be in the desired environment path and run:
```
ansible-playbook -i inventory.yml destroy.yml
```

</details>

## Provisioning

With ansible(playbook, inventory) we can deploy a few types of environments(both deployment and provisioning are performed together):


<details>

<summary><code>agentless_cluster</code></summary>

- `wazuh-master`
- `wazuh-worker1`
- `wazuh-worker2`

</details>

<details>

<summary><code>basic_cluster</code></summary>

- `wazuh-master`
- `wazuh-worker1`
- `wazuh-worker2`
- `wazuh-agent1`
- `wazuh-agent2`
- `wazuh-agent3`

</details>

<details>

<summary><code>basic_environment</code></summary>

- `wazuh-master`
- `wazuh-agent1`

</details>

<details>

<summary><code>enrollment_cluster</code></summary>

- `wazuh-master`
- `wazuh-worker1`
- `wazuh-worker2`
- `wazuh-agent1`

</details>

<details>

<summary><code>manager_agent</code></summary>

- `wazuh-master`
- `wazuh-agent1`
- `wazuh-agent2`
- `wazuh-agent3`

</details>

<details>

<summary><code>one_manager_agent</code></summary>

- `wazuh-master`
- `wazuh-agent1`

</details>

---

These provisioning types have the following files:
- `destroy.yml`
- `inventory.yml`
- `playbook.yml`

Where most of them are equal(e.g, when creating `wazuh-worker2` with `playbook.yml` files or destroying some component)
Also the `ansible.cfg` is equal.

## Framework components

### HostManager

Ansible wrapper that is used to modify/run/control the remote host via ansible python api.

### HostMonitor

Monitors remote files to verify that expected events are taking place. This class has a path to a file which has the callbacks and timeouts


```
wazuh-worker2:
  - regex: '.*Received.*shared files to update from .*'
    path: "/var/ossec/logs/cluster.log"
    timeout: 60
  - regex: '.*Worker wazuh-worker2.*Integrity sync.*Finished in.*'
    path: "/var/ossec/logs/cluster.log"
    timeout: 60
  - regex: '.*Worker wazuh-worker2.*Integrity sync.*Starting.*'
    path: "/var/ossec/logs/cluster.log"
    timeout: 60
  - regex: '.*Worker wazuh-worker2.*Integrity sync.*Finished in.*'
    path: "/var/ossec/logs/cluster.log"
    timeout: 60

wazuh-master:
  - regex: '.*Worker wazuh-worker2.*Integrity check.*Finished in.*'
    path: "/var/ossec/logs/cluster.log"
    timeout: 60
```

For every path within each host a process is created, monitoring that file using a regex.

Threads are created and allocated in `_file_monitors`(`file_composer`) and `_file_content_collectors`(`_start`). For each desired file, the file content is dumped into the `output_path` file. Then, it monitors that `output_path` using a `QueueMonitor`. Finally, it collects the results that have been inserted into the queue.

When a thread ends, the result is added to the `result` dictionary with the host key. If the message is a `TimeoutError` it performs a raise(only reporting one  error if there are more errors just the first one shows up).


## Pros/Cons

## Deployment

- Pros
  - Docker containers deployment is so fast
  - Both local and jenkins automation develop

- Cons
  - It has system limitation, only debian can be used
  - Deployment and provisioning are performed at the same time
  - For every deploy you must navigate to its path 
  - If we have a wrong environment, we have to destroy it and deploy it again 
  - Differents environments types cannot be deployed at the same time

## Provisioning

- Pros
  - Unattended

- Cons
  - It compiles the source code instead of use a package
  - Duplicated snippets -> playbooks, inventory, etc.
  - Once deployed and provisioned, you cannot run with another wazuh(-qa) branch

## Testing

- Pros
  - Allows running system test so easy

- Cons
  - Each test type is different
  - Most of them, has no setup/teardown
  - Unstable framework
  - A report when having errors its needed
  - Tests do not support all systems
  - We cannot run different system combinations
