### ISSUE TITLE
qa-docs: Review current schema since framework changes

### ISSUE THREAD

**Issue by roronoasins** [wazuh/wazuh-qa#2590]
# Description
The framework has received changes since the last schema design, we have also worked in #2588. These changes may make the schema obsolete, so we need to research if we need to update the current doc schema we are using.

# Tasks
- [x] Research about changing the schema
- [x] Change the `schema.yaml`

**Comment by roronoasins** [comment]
This would be the `schema.yaml` file content related to the fields:

```yaml
  module:
    mandatory:
      - copyright
      - type
      - brief
      - component
      - suite
      - targets
      - daemons
      - os_platform
      - os_version
    optional:
      - references
      - pytest_args
      - tags
    auto:
      - path
  test:
    mandatory:
      - description
      - wazuh_min_version
      - tier
      - parameters
      - assertions
      - input_description
    optional:
      - expected_output
      - inputs
      - tags
```

Then, the predefined values will change according to the new/modified fields.
