### ISSUE TITLE
System tests: Deployment file design

### ISSUE THREAD

**Issue by roronoasins** [wazuh/wazuh-qa#2789]
# Description
As we are working on the system tests rework, we need to change the deployment to satisfy the rework requirements.

# Tasks
- [x] First proposal
- [x] Ask for feedback
- [x] Refine proposal/Get final proposal

**Comment by roronoasins** [comment]
# First proposal

## Schema

- `host`(str): select the type of host to deploy (manager, worker, agent, indexer, dashboard)
- `role`(list): role selection (manager, work, active-agent, passive-agent, etc.)
- `number`(int): number of instances with the properties specified in the file (optional)
- `os`(list): field that allows selecting the os for each instance

## Sample

One master, two workers, one indexer, one dashboard, and four agents

```yaml
- 
  host: master
  role:
    - master
    - filebeat
  os: 
    - ubuntu

- 
  host: worker
  role:
    - worker
    - master
  number: 2
  os: 
    - ubuntu
    - centos

-
  host: indexer
  os:
    - centos

-
  host: dashboard
  os:
    - centos

- 
  host: agent
  role:
    - active-agent
  number: 4
  os: 
    - centos
    - windows
    - solaris
    - macos
```

## Dynamic metadata

`resources` -> CPU/Mem algorithm based on the environment
`default os` -> The deployment framework will determine it if it is not specified in the deployment file
