### ISSUE TITLE
Release 4.3.0 - Manual tests - Configuration assesment

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#2834]
The following issue aims to run the specified test for the current release candidate, report the results, and open new issues for any encountered errors.

## Test information
|                         |                                            |
|-------------------------|--------------------------------------------|
| **Test name**           |   Configuration assesment                                         |
| **Category**            |     Installation                                       |
| **Deployment option**   |    Offline installation                                        |
| **Main release issue**  |     https://github.com/wazuh/wazuh/issues/10954                                       |
| **Release candidate #** |     RC6                                       |

## Test description
- [ ] Try SCA policy for amazon Linux 2 (https://github.com/wazuh/wazuh/pull/11480)
- [ ] Try SCA policy for nginx (https://github.com/wazuh/wazuh/pull/11248)

## Test report procedure

All test results must have one of the following statuses: 
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| :green_circle:  | All checks passed. |
| :red_circle:    | There is at least one failed result. |
| :yellow_circle:  | There is at least one expected failure or skipped test and no failures. |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause. 

An extended report of the test results must be attached as a ZIP or TXT file. Please attach any documents, screenshots, or tables to the issue update with the results. This report can be used by the auditors to dig deeper into any possible failures and details.

## Conclusions

All tests have been executed and the results can be found [here]().

|                |             |                     |                |
|----------------|-------------|---------------------|----------------|
| **Status**     | **Test**    | **Failure type**    | **Notes**      |
| :black_circle: | SCA for Amazon Linux 2 | |
| :black_circle: | SCA for NGINX |  |

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [ ] @72nomada   
- [ ] @jmv74211

**Comment by Rebits** [comment]
### 28/04/2022
# Offline installation All-In-One :green_circle: 
## Download the packages and configuration files

<details>

- Download wazuh-install script
```
[root@ip-172-31-81-41 ~]#  ./wazuh-install.sh -dw rpm
28/04/2022 09:07:08 INFO: Starting Wazuh installation assistant. Wazuh version: 4.3.0
28/04/2022 09:07:08 INFO: Verbose logging redirected to /var/log/wazuh-install.log
28/04/2022 09:07:10 INFO: --- Download Packages ---
28/04/2022 09:07:10 INFO: Starting Wazuh packages download.
28/04/2022 09:07:10 INFO: Downloading Wazuh rpm packages for x86_64.
28/04/2022 09:07:11 INFO: The manager package was downloaded.
28/04/2022 09:07:11 INFO: The filebeat package was downloaded.
28/04/2022 09:07:13 INFO: The indexer package was downloaded.
28/04/2022 09:07:14 INFO: The dashboard package was downloaded.
28/04/2022 09:07:14 INFO: The packages are in wazuh-offline/wazuh-packages
28/04/2022 09:07:14 INFO: Downloading configuration files and assets.
28/04/2022 09:07:14 INFO: The resource https://packages-dev.wazuh.com/key/GPG-KEY-WAZUH was downloaded.
28/04/2022 09:07:14 INFO: The resource https://packages-dev.wazuh.com/4.3/tpl/wazuh/filebeat/filebeat.yml was downloaded.
28/04/2022 09:07:15 INFO: The resource https://raw.githubusercontent.com/wazuh/wazuh/4.3/extensions/elasticsearch/7.x/wazuh-template.json was downloaded.
28/04/2022 09:07:15 INFO: The resource https://packages-dev.wazuh.com/pre-release/filebeat/wazuh-filebeat-0.1.tar.gz was downloaded.
28/04/2022 09:07:15 INFO: The configuration files and assets are in wazuh-offline/wazuh-files
28/04/2022 09:07:39 INFO: You can follow the installation guide here https://documentation.wazuh.com/current/installation-guide/more-installation-alternatives/offline-installation.html
[root@ip-172-31-81-41 ~]# 
``` 
- `config.yaml`
```
nodes:
  # Wazuh indexer nodes
  indexer:
    - name: node-1
      ip: 127.0.0.1
    # - name: node-2
    #   ip: <indexer-node-ip>
    # - name: node-3
    #   ip: <indexer-node-ip>

  # Wazuh server nodes
  # Use node_type only with more than one Wazuh manager
  server:
    - name: wazuh-1
      ip: 127.0.0.1
    # node_type: master
    # - name: wazuh-2
    #   ip: <wazuh-manager-ip>
    # node_type: worker

  # Wazuh dashboard nodes
  dashboard:
    - name: dashboard
      ip: 127.0.0.1
~                    
```
- Certificates creation
```
root@ip-172-31-81-41 ec2-user]# ./wazuh-certs-tool.sh --all 
28/04/2022 08:04:29 INFO: Admin certificates created.
28/04/2022 08:04:29 INFO: Wazuh indexer certificates created.
28/04/2022 08:04:29 INFO: Wazuh server certificates created.
28/04/2022 08:04:30 INFO: Wazuh dashboard certificates created.
```

</details>


## Installing Wazuh indexer


<details>

- Install wazuh-indexer (rpm)
```
[root@ip-172-31-81-41 ec2-user]# rpm -ivh ./wazuh-offline/wazuh-packages/wazuh-indexer*.rpm
warning: ./wazuh-offline/wazuh-packages/wazuh-indexer-4.3.0-1.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID 29111145: NOKEY
Preparing...                          ################################# [100%]
Updating / installing...
   1:wazuh-indexer-4.3.0-1            ################################# [100%]
Created opensearch keystore in /etc/wazuh-indexer/opensearch.keystore
```

- Set certificates
```
[root@ip-172-31-81-41 ec2-user]#  mv -n wazuh-certificates/node-1-key.pem /etc/wazuh-indexer/certs/indexer-key.pem
[root@ip-172-31-81-41 ec2-user]# mv wazuh-certificates/admin-key.pem /etc/wazuh-indexer/certs/
[root@ip-172-31-81-41 ec2-user]# mv wazuh-certificates/admin.pem /etc/wazuh-indexer/certs/
[root@ip-172-31-81-41 ec2-user]# cp wazuh-certificates/root-ca.pem /etc/wazuh-indexer/certs/
[root@ip-172-31-81-41 ec2-user]# chmod 500 /etc/wazuh-indexer/certs
[root@ip-172-31-81-41 ec2-user]# 
[root@ip-172-31-81-41 ec2-user]# chmod 400 /etc/wazuh-indexer/certs/*
[root@ip-172-31-81-41 ec2-user]# 
[root@ip-172-31-81-41 ec2-user]# chown -R wazuh-indexer:wazuh-indexer /etc/wazuh-indexer/certs
```

- Security init
```
[root@ip-172-31-81-41 ec2-user]# /usr/share/wazuh-indexer/bin/indexer-security-init.sh
Security Admin v7
Will connect to 127.0.0.1:9300 ... done
Connected as CN=admin,OU=Wazuh,O=Wazuh,L=California,C=US
OpenSearch Version: 1.2.4
OpenSearch Security Version: 1.2.4.0
Contacting opensearch cluster 'opensearch' and wait for YELLOW clusterstate ...
Clustername: wazuh-cluster
Clusterstate: YELLOW
Number of nodes: 1
Number of data nodes: 1
.opendistro_security index already exists, so we do not need to create one.
Populate config from /usr/share/wazuh-indexer/plugins/opensearch-security/securityconfig/
Will update '_doc/config' with /usr/share/wazuh-indexer/plugins/opensearch-security/securityconfig/config.yml 
   SUCC: Configuration for 'config' created or updated
Will update '_doc/roles' with /usr/share/wazuh-indexer/plugins/opensearch-security/securityconfig/roles.yml 
   SUCC: Configuration for 'roles' created or updated
Will update '_doc/rolesmapping' with /usr/share/wazuh-indexer/plugins/opensearch-security/securityconfig/roles_mapping.yml 
   SUCC: Configuration for 'rolesmapping' created or updated
Will update '_doc/internalusers' with /usr/share/wazuh-indexer/plugins/opensearch-security/securityconfig/internal_users.yml 
   SUCC: Configuration for 'internalusers' created or updated
Will update '_doc/actiongroups' with /usr/share/wazuh-indexer/plugins/opensearch-security/securityconfig/action_groups.yml 
   SUCC: Configuration for 'actiongroups' created or updated
Will update '_doc/tenants' with /usr/share/wazuh-indexer/plugins/opensearch-security/securityconfig/tenants.yml 
   SUCC: Configuration for 'tenants' created or updated
Will update '_doc/nodesdn' with /usr/share/wazuh-indexer/plugins/opensearch-security/securityconfig/nodes_dn.yml 
   SUCC: Configuration for 'nodesdn' created or updated
Will update '_doc/whitelist' with /usr/share/wazuh-indexer/plugins/opensearch-security/securityconfig/whitelist.yml 
   SUCC: Configuration for 'whitelist' created or updated
Will update '_doc/audit' with /usr/share/wazuh-indexer/plugins/opensearch-security/securityconfig/audit.yml 
   SUCC: Configuration for 'audit' created or updated
Done with success
```

- `opensearch.yaml`
```
network.host: "172.0.0.1"
node.name: "node-1"
cluster.initial_master_nodes:
- "node-1"
#- "node-2"
#- "node-3"
...
```

</details>

```
[root@ip-172-31-81-41 ec2-user]# curl -XGET https://localhost:9200 -u admin:admin -k
{
  "name" : "node-1",
  "cluster_name" : "wazuh-cluster",
  "cluster_uuid" : "vJSKzLbKTxOP_P-TuDmF_Q",
  "version" : {
    "number" : "7.10.2",
    "build_type" : "rpm",
    "build_hash" : "e505b10357c03ae8d26d675172402f2f2144ef0f",
    "build_date" : "2022-01-14T03:38:06.881862Z",
    "build_snapshot" : false,
    "lucene_version" : "8.10.1",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "The OpenSearch Project: https://opensearch.org/"
}
```


## Installing the Wazuh server




<details>
- Installing wazuh-server (rpm)

```
[root@ip-172-31-81-41 ec2-user]# rpm --import ./wazuh-offline/wazuh-files/GPG-KEY-WAZUH
[root@ip-172-31-81-41 ec2-user]# rpm -ivh ./wazuh-offline/wazuh-packages/wazuh-manager*.rpm
Preparing...                          
################################# [100%]
Updating / installing...
   1:wazuh-manager-4.3.0-1            ################################# [100%]
[root@ip-172-31-81-41 ec2-user]# 
[root@ip-172-31-81-41 ec2-user]# systemctl daemon-reload
[root@ip-172-31-81-41 ec2-user]# systemctl enable wazuh-manager
Created symlink from /etc/systemd/system/multi-user.target.wants/wazuh-manager.service to /usr/lib/systemd/system/wazuh-manager.service.
[root@ip-172-31-81-41 ec2-user]# 
[root@ip-172-31-81-41 ec2-user]# systemctl start wazuh-manager
```
</details>

```
[root@ip-172-31-81-41 ec2-user]# systemctl status wazuh-manager
● wazuh-manager.service - Wazuh manager
   Loaded: loaded (/usr/lib/systemd/system/wazuh-manager.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2022-04-28 08:28:25 UTC; 1s ago
  Process: 4576 ExecStart=/usr/bin/env /var/ossec/bin/wazuh-control start (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/wazuh-manager.service
           ├─4632 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
           ├─4674 /var/ossec/bin/wazuh-authd
           ├─4691 /var/ossec/bin/wazuh-db
           ├─4703 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
           ├─4706 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
           ├─4721 /var/ossec/bin/wazuh-execd
           ├─4736 /var/ossec/bin/wazuh-analysisd
           ├─4779 /var/ossec/bin/wazuh-syscheckd
           ├─4795 /var/ossec/bin/wazuh-remoted
           ├─4832 /var/ossec/bin/wazuh-logcollector
           ├─4853 /var/ossec/bin/wazuh-monitord
           ├─4873 /var/ossec/bin/wazuh-modulesd
           ├─5011 sh -c  yum check-updates --security | grep "No packages"
           ├─5013 /usr/bin/python /usr/bin/yum check-updates --security
           ├─5014 grep No packages
           └─5151 /var/ossec/bin/wazuh-syscheckd

Apr 28 08:28:16 ip-172-31-81-41.ec2.internal env[4576]: Started wazuh-db...
Apr 28 08:28:17 ip-172-31-81-41.ec2.internal env[4576]: Started wazuh-execd...
Apr 28 08:28:18 ip-172-31-81-41.ec2.internal env[4576]: Started wazuh-analysisd...
Apr 28 08:28:19 ip-172-31-81-41.ec2.internal env[4576]: Started wazuh-syscheckd...
Apr 28 08:28:20 ip-172-31-81-41.ec2.internal env[4576]: Started wazuh-remoted...
Apr 28 08:28:21 ip-172-31-81-41.ec2.internal env[4576]: Started wazuh-logcollector...
Apr 28 08:28:22 ip-172-31-81-41.ec2.internal env[4576]: Started wazuh-monitord...
Apr 28 08:28:23 ip-172-31-81-41.ec2.internal env[4576]: Started wazuh-modulesd...
Apr 28 08:28:25 ip-172-31-81-41.ec2.internal env[4576]: Completed.
Apr 28 08:28:25 ip-172-31-81-41.ec2.internal systemd[1]: Started Wazuh manager.
[root@ip-172-31-81-41 ec2-user]# 
```

## Installing Filebeat

<details>

- Installing Filebeat (rpm)

```
[root@ip-172-31-81-41 ec2-user]# rpm -ivh ./wazuh-offline/wazuh-packages/filebeat*.rpm
Preparing...                          ################################# [100%]
Updating / installing...
   1:filebeat-7.10.2-1                ################################# [100%]
[root@ip-172-31-81-41 ec2-user]# cp ./wazuh-offline/wazuh-files/filebeat.yml /etc/filebeat/ &&\
> cp ./wazuh-offline/wazuh-files/wazuh-template.json /etc/filebeat/ &&\
> chmod go+r /etc/filebeat/wazuh-template.json
cp: overwrite ‘/etc/filebeat/filebeat.yml’? y
```

- `filebeat.yaml`
```
# Wazuh - Filebeat configuration file
output.elasticsearch:
  hosts: ["127.0.0.1:9200"]
  protocol: https
  username: admin
  password: admin
  ssl.certificate_authorities:
    - /etc/filebeat/certs/root-ca.pem
  ssl.certificate: "/etc/filebeat/certs/filebeat.pem"
  ssl.key: "/etc/filebeat/certs/filebeat-key.pem"
setup.template.json.enabled: true
setup.template.json.path: '/etc/filebeat/wazuh-template.json'
setup.template.json.name: 'wazuh'
setup.ilm.overwrite: true
setup.ilm.enabled: false

filebeat.modules:
  - module: wazuh
    alerts:
      enabled: true
    archives:
      enabled: false

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644
```

- Certificates assesment

```
[root@ip-172-31-81-41 ec2-user]#  chmod 500 /etc/filebeat/certs
[root@ip-172-31-81-41 ec2-user]# chmod 400 /etc/filebeat/certs/*
[root@ip-172-31-81-41 ec2-user]# chown -R root:root /etc/filebeat/certs
```

- Start filebeat process
- 
```
[root@ip-172-31-81-41 ec2-user]# systemctl daemon-reload
[root@ip-172-31-81-41 ec2-user]# systemctl enable filebeat
Created symlink from /etc/systemd/system/multi-user.target.wants/filebeat.service to /usr/lib/systemd/system/filebeat.service.
[root@ip-172-31-81-41 ec2-user]# 
[root@ip-172-31-81-41 ec2-user]# systemctl start filebeat
```
 
</details>

```
[root@ip-172-31-81-41 ec2-user]# filebeat test output
elasticsearch: https://127.0.0.1:9200...
  parse url... OK
  connection...
    parse host... OK
    dns lookup... OK
    addresses: 127.0.0.1
    dial up... OK
  TLS...
    security: server's certificate chain verification is enabled
    handshake... OK
    TLS version: TLSv1.3
    dial up... OK
  talk to server... OK
  version: 7.10.2
```

```
[root@ip-172-31-81-41 ec2-user]# curl -k -u admin:admin "https://127.0.0.1:9200/_template/wazuh?pretty&filter_path=wazuh.settings.index.number_of_shards"
{
  "wazuh" : {
    "settings" : {
      "index" : {
        "number_of_shards" : "1"
      }
    }
  }
}

```



## Installing Wazuh dashboard


<details>



</details>

**Comment by Rebits** [comment]
### 28/04/2022
# Try SCA policy for amazon Linux 2

Using default configuration
```
  <sca>
    <enabled>yes</enabled>
    <scan_on_start>yes</scan_on_start>
    <interval>12h</interval>
    <skip_nfs>yes</skip_nfs>
  </sca>
```

We can see that `Security configuration assessment` dashboard menu shows ALAS2 scans

![SCA-ALAS](https://user-images.githubusercontent.com/11089305/165729100-66fc2cf1-237b-4d7e-816b-1454d4290899.png)

-  [ALAS 2 SCA scan archives](https://github.com/wazuh/wazuh-qa/files/8581731/On_demand_report_2022-04-28T09.48.36.207Z_5fad47f0-c6d8-11ec-8a81-49d5a7c88e80.csv)

**Comment by Rebits** [comment]
### 28/04/2022
# Custom policy creation

- `ossec.conf`
```
  <sca>
   <policies>
    <policy>/tmp/custom_policy.yml</policy>
   </policies>
    <enabled>yes</enabled>
    <scan_on_start>yes</scan_on_start>
    <interval>12h</interval>
    <skip_nfs>yes</skip_nfs>
  </sca>
```

- `custom_policy.yaml`
```
policy:
  id: "custom_policy"
  file: "custom_policy.yml"
  name: "Testing custom policy"
  description: "Custom policy testing"
  references:
    - https://www.ssh.com/ssh/

variables:
  $testing_file: /tmp/testing_file.txt

requirements:
  title: "Check that the testing file exists"
  description: "Testing file to check policy"
  condition: any
  rules:
    - 'f:$testing_file'

checks:
  - id: 10000
    title: "TESTING"
    description: "TESTING CUSTOM POLICY"
    rationale: "Rationale"
    remediation: "Remediation"
    compliance:
      - pci_dss: ["2.2.4"]
      - nist_800_53: ["CM.1"]
    condition: all
    rules:
     - 'f:$testing_file -> r:^\s*TestingFailedCondition\s*\t*no'

```

- Custom policy pass
![custom_policy](https://user-images.githubusercontent.com/11089305/165733576-965c351a-3a0b-4b57-bc3f-a21dd143bc69.png)


- Custom policy fail
![pass_to_fail](https://user-images.githubusercontent.com/11089305/165740679-fea64294-74af-4065-9dfa-f09f3918c783.png)
