### ISSUE TITLE
E2E design and implementation: RDP Brute force

### ISSUE THREAD

**Issue by BelenValdivia** [wazuh/wazuh-qa#3026]
## Description

The test research was accomplished in [this issue](https://github.com/wazuh/wazuh-qa/issues/2838). So, in this issue, we will design and develop the E2E test to cover those use cases.

## Tasks

- [x] Design the test
- [x] Implement the test locally
- [ ] Refactor the test for it to work in the test environment

## Conclusion

[An existing test was modified](https://github.com/wazuh/wazuh-qa/pull/2938) to implement this test case. `hydra` was utilized to generate the RDP event and the unique requirement to execute this test is to create an inventory as follows:

```
all:
  hosts:
    wazuh-manager:
      ansible_connection: ssh
      ansible_user: ...
      ansible_password: ...
      ansible_ssh_private_key_file: ...
      ansible_python_interpreter: ...
      dashboard_user: ...
      dashboard_password: ...
  children:
    agents:
      hosts:
        wazuh-agent:
          ansible_connection: ssh
          ansible_user: ...
          ansible_password: ...
          ansible_ssh_private_key_file: ...
          ansible_python_interpreter: ...
        wazuh-windows:
          ansible_user: ...
          ansible_password: ...
          ansible_connection: winrm
          ansible_winrm_server_cert_validation: ignore
          ansible_winrm_transport: basic
          ansible_winrm_port: 5985
          ansible_python_interpreter: ...
```
