### ISSUE TITLE
E2E design and implementation: Yara

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#3085]
## Description

The test research was accomplished in [this issue](https://github.com/wazuh/wazuh-qa/issues/2860). So, in this issue, we will design and develop the E2E test to cover those use cases.

## Tasks

- [x] Design the test
- [x] Implement the test locally
- [ ] Refactor the test for it to work in the test environment

## Conclusion

WIP.

**Comment by juliamagan** [comment]
On Hold because of [Release Candidate Manual Testing](https://github.com/wazuh/wazuh-qa/issues/3101).

**Comment by mauromalara** [comment]
## Task 1: Design the test 🟢

The added module tests the integration with Yara. The only precondition to run is to create an inventory as follows:
```
all:
  hosts:
    wazuh-manager:
      ansible_connection: ssh
      ansible_user: <VM USER>
      ansible_ssh_private_key_file: <PRIVATE KEY PATH>
      ansible_python_interpreter: <PYTHON INTERPRETER PATH>
      dashboard_user: <USER>
      dashboard_password: <PASS>
```

The test structure is the following:

```
tests/end_to_end/test_yara_integration/
├── data
│   ├── configuration
│   │   ├── malware_downloader.sh
│   │   └── yara.sh
│   ├── playbooks
│   │   ├── configuration.yaml
│   │   ├── generate_events.yaml
│   │   └── teardown.yaml
│   └── test_cases
│       └── cases_yara_integration.yaml
└── test_yara_integration.py
```

+ `configuration`: this folder contains all necessary scripts to generate the events that must trigger alerts in the manager.
+ `playbooks`: this folder contains all necessary Ansible playbooks to (1) prepare the environment, (2) generate the events and get alerts, and (3) clean the environment.
+ `test_cases`: this folder contains a YAML file with the test cases that will be executed in this test (in this stage we will only create 1 test case).
+ `test_yara_integration.py`: this is the module that test the integration.
