### ISSUE TITLE
Release 4.3.7 - Release Candidate 1 - E2E UX tests - Wazuh Dashboard

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3176]
The following issue aims to run the specified test for the current release candidate, report the results, and open new issues for any encountered errors.
## Modules tests information

|||
|----------------------------------|------ |
| **Main release candidate issue** | [#14562](https://github.com/wazuh/wazuh/issues/14562)     |
| **Main E2E UX test issue** | [#14614](https://github.com/wazuh/wazuh/issues/14614)    |
| **Version**                      | 4.3.7 |
| **Release candidate #**          | RC1   |
| **Tag**                          | [v4.3.7-rc1](https://github.com/wazuh/wazuh/tree/v4.3.7-rc1) |
| **Previous modules tests issue** |    |

## Installation procedure
- Wazuh Indexer
  - [Step by Step](https://documentation.wazuh.com/current/installation-guide/wazuh-indexer/step-by-step.html)
- Wazuh Server
  - [Step by Step](https://documentation.wazuh.com/current/installation-guide/wazuh-indexer/step-by-step.html)
- Wazuh Dashboard
  - [Step by Step](https://documentation.wazuh.com/current/installation-guide/wazuh-indexer/step-by-step.html)
- Wazuh Agent
  - Wazuh WUI one-liner deploy IP GROUP (created beforehand)

## Test description

Best efford to test Wazuh dashboard package. Think critically and at least review/test:

 - [x] [Wazuh dashboard package specs](https://github.com/wazuh/wazuh-qa/issues/3176#issuecomment-1217898090)
 - [x] [Dashboard package size](https://github.com/wazuh/wazuh-qa/issues/3176#issuecomment-1217915330)
 - [x] [Dashboard package metadata (description)](https://github.com/wazuh/wazuh-qa/issues/3176#issuecomment-1217990799)
 - [x] [Dashboard package digital signature](https://github.com/wazuh/wazuh-qa/issues/3176#issuecomment-1218140697)
 - [x] [Installed files location, size and permissions](https://github.com/wazuh/wazuh-qa/issues/3176#issuecomment-1218228264)
 - [x] [Installation footprint (check that no unnecessary files are modified/broken in the file system. For example that operating system files do keep their right owner/pemissions and that the installer did not break the system.)](https://github.com/wazuh/wazuh-qa/issues/3176#issuecomment-1218373582)
 - [x] [Installed service (test that it works correctly)](https://github.com/wazuh/wazuh-qa/issues/3176#issuecomment-1218376807)
 - [x] [Wazuh Dashboard logs when installed](https://github.com/wazuh/wazuh-qa/issues/3176#issuecomment-1219419831)
 - [x] [Wazuh Dashboard configuration (Try to find anomalies compared with 4.3.6)](https://github.com/wazuh/wazuh-qa/issues/3176#issuecomment-1219494469)
 - [x] [Wazuh Dashboard (included the Wazuh WUI) communication with Wazuh manager API and Wazuh indexer](https://github.com/wazuh/wazuh-qa/issues/3176#issuecomment-1219661168)
 - [x] [Register Wazuh Agents](https://github.com/wazuh/wazuh-qa/issues/3176#issuecomment-1219742384)
 - [x] [Basic browsing throguh the WUI](https://github.com/wazuh/wazuh-qa/issues/3176#issuecomment-1220027690)
 - [x] [Basic experience with WUI performance.](https://github.com/wazuh/wazuh-qa/issues/3176#issuecomment-1220033939)
 - [x] [Anything else that could have been overlooked when creating the new package](https://github.com/wazuh/wazuh-qa/issues/3176#issuecomment-1220033939)

## Test report procedure

All test results must have one of the following statuses: 
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| :green_circle:  | All checks passed. |
| :red_circle:  | There is at least one failed result. |
| :yellow_circle:  | There is at least one expected failure or skipped test and no failures. |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause. 

An extended report of the test results can be attached as a ZIP or TXT file. Please attach any documents, screenshots, or tables to the issue update with the results. This report can be used by the auditors to dig deeper into any possible failures and details.

## Conclusions

All tests have been executed and the results can be found in the issue updates.

| **Status**     | **Test**    | **Failure type**    | **Notes**      |
|----------------|-------------|---------------------|----------------|
| :green_circle: | Wazuh dashboard package specs | Functional |  
| :green_circle: | Dashboard package size  | Functional |  
| :green_circle: | Dashboard package metadata (description) | Usability |  
| :green_circle: | Dashboard package digital signature | Usability |  
| :green_circle: | Installed files location, size and permissions  | Functional |  
| :green_circle: | Installation footprint  | Functional |  
| :green_circle: | Wazuh Dashboard logs when installed  | Functional | 
| :green_circle: | Wazuh Dashboard configuration  | Functional | 
| :green_circle: | Wazuh Dashboard (included the Wazuh WUI) communication with Wazuh manager API and Wazuh indexer | Functional |  
| :green_circle: | Register Wazuh Agents  | Functional |  
| :green_circle: | Basic browsing through the WUI | Usability |  
| :green_circle: | Basic experience with WUI performance | Usability |  

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [x] @jmv74211 
- [x] @vikman90

**Comment by QU3B1M** [comment]
# Wazuh Dashboard Package Specs

```yaml
apt show ./wazuh-dashboard_4.3.7-1_amd64.deb 

Package: wazuh-dashboard
Version: 4.3.7-1
Priority: extra
Section: admin
Maintainer: Wazuh, Inc <info@wazuh.com>
Installed-Size: 638 MB
Depends: debconf, adduser, curl, tar, libcap2-bin
Homepage: https://www.wazuh.com
Download-Size: 131 MB
APT-Manual-Installed: yes
APT-Sources: /vagrant/wazuh-dashboard_4.3.7-1_amd64.deb
Description: Wazuh dashboard is a user interface and visualization tool for security-related data. This Wazuh central component enables exploring, visualizing, and analyzing the stored security alerts generated by the Wazuh server. Wazuh dashboard enables inspecting the status and managing the configurations of the Wazuh cluster and agents as well as creating and managing users and roles. In addition, it allows testing the ruleset and making calls to the Wazuh API. Documentation can be found at https://documentation.wazuh.com/current/getting-started/components/wazuh-dashboard.html

```


![image](https://user-images.githubusercontent.com/44633633/185109356-3cd58d9b-8c1a-4182-9bc5-cadcf2c35707.png)
