### ISSUE TITLE
E2E - Adapt environment validation to Jenkins automation tools

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#3237]
| Related issue |
|----| 
|#3194|
## Description
Regarded https://github.com/wazuh/wazuh-qa/issues/3194 development, we need to adapt the validation of E2E tests to the inventory provided by the automation tools.

### Current behavior
Currently, the inventory generated by Jenkins automation tools follows this structure:

<details>

```
manager:
  hosts:
    centos-manager:
...
      os_name: linux
  vars: {}
indexer:
  hosts:
    centos-manager:
...
  vars: {}
filebeat:
  hosts:
...
  vars: {}
agent:
  children:
    linux:
      hosts:
        ubuntu-agent:
...
        centos-agent:
...
    macos:
      hosts: {}
    solaris:
      hosts: {}
    windows:
      hosts:
        windows-agent:
....
all:
  vars:
    ansible_ssh_common_args: -o StrictHostKeyChecking=no
...
```

However, the validation stage proceeds with a strict validation, failing if more hosts than required are provided.

</details>

### Expected behavior

The validation process should only check that required hosts are provided and configured, ignoring the rest of the hosts provided in the inventory.
