### ISSUE TITLE
Verify the engine's Ruleset behavior 

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3535]
| Target version | Related issue | Related PR/dev branch |
|--------------------|--------------------|-----------------|
|           5.0             |         https://github.com/wazuh/wazuh-qa/issues/3533          |          https://github.com/wazuh/wazuh/issues/11334          |

## Description

Since the team is reworking the engine, we need to cover this new engine rework. This issue will test the new engine to ensure all is correct. 

## Proposed test cases

- [x] `Ruleset:` We want to test a correct input returns a valid result, an incorrect input returns an error and an unexpected input doesn't crash the program. The module to test are:
  - [x] Follow the ruleset(decoder and env management) guide within the dev guide 

## Considerations
The threat intel team has started with the new engine, so when they add the ruleset to the env, we will check that all the added ruleset works.

**Comment by roronoasins** [comment]
## 2022/11/02

Today I have started the ruleset guide within the engine environment guide from the dev team. The last vagrantfile version was used but code-server could not connect(maybe due to resources).

I will continue with this until the API or events issue is solved.

**Comment by roronoasins** [comment]
## Task results

### Follow the ruleset dev guide

> I used the code-server feature by connecting to `ip:8040`

1. Add a custom decoder to `ruleset/decoders`

<details><summary><code>decoder/apache-access/0</code> decoder</summary>

```
name: decoder/apache-access/0

metadata:
  description: Parses Apache HTTPD access logs in its Common Log Format
  references: [
    "https://httpd.apache.org/docs/2.4/mod/core.html#errorlogformat",
    "https://en.wikipedia.org/wiki/Apache_Commons_Logging"
  ]
  product.name: apache
  product.version: 2.x
  author.name: wazuh
  author.mail: https://github.com/wazuh/wazuh

sources:
 - decoder/queue-localfile/0

check:
 - event.original: +ef_exists 

parse:
 logpar:
    # 192.168.10.1 - - [10/Jul/1992:10:07:13 +0200] "GET /someicon.ico HTTP/1.1" 404 209 
    - event.original: <source.ip> - - [<event.created/HTTPDATE>] "<http.request.method> <url.original> HTTP/<http.version>" <http.response.status_code> <http.response.body.bytes>

normalize:
  - map:
    - event.kind: event
    - event.dataset: apache.access
    - event.category: +a_append/web
    - event.module: apache
    - service.type: apache
    - event.outcome: success
  - check:
      - http.response.status_code: +i_gt/399
    map:
      - event.outcome: failure

```

</details>

2. Check if it is valid
    ```
    root@engine:/home/vagrant/engine/wazuh/src/engine# /var/ossec/engine/wazuh-engine catalog validate decoder/apache-access/0 < ruleset/decoders/apache-access.yml 
    OK
    ```

3. Push the decoder to the catalog storage
    ```
    root@engine:/home/vagrant/engine/wazuh/src/engine# /var/ossec/engine/wazuh-engine catalog create decoder < ruleset/decoders/apache-access.yml 
    OK
    ```

4. Update the wazuh environment so the decoder is applied
    ```
    root@engine:/home/vagrant/engine/wazuh/src/engine# /var/ossec/engine/wazuh-engine catalog update environment/wazuh/0 < ruleset/environments/wazuh-environment.yml 
    OK
    ```

5. Verify the decoder is now available
    ```
    root@engine:/home/vagrant/engine/wazuh/src/engine# /var/ossec/engine/wazuh-engine catalog get environment/wazuh/0
    name: environment/wazuh/0
    decoders:
      - decoder/queue-syscollector/0
      - decoder/queue-sca/0
      - decoder/queue-fim/0
      - decoder/queue-syslog/0
      - decoder/queue-dbsync/0
      - decoder/queue-localfile/0
      - decoder/queue-rootcheck/0
      - decoder/json/0
      - decoder/dbsync/0
      - decoder/fim/0
      - decoder/fim-event/0
      - decoder/fim-scan/0
      - decoder/rootcheck/0
      - decoder/sca/0
      - decoder/syscollector-base/0
      - decoder/syscollector-dbsync-network-protocol/0
      - decoder/syscollector-dbsync-osinfo/0
      - decoder/syscollector-dbsync-osinfo-inserted/0
      - decoder/syscollector-dbsync-ports/0
      - decoder/syscollector-dbsync-ports-inserted/0
      - decoder/syscollector-dbsync-processes/0
      - decoder/syscollector-dbsync-processes-inserted/0
      - decoder/syscollector-dbsync-base/0
      - decoder/syscollector-dbsync-hotfixes/0
      - decoder/syscollector-dbsync-hotfixes-inserted/0
      - decoder/syscollector-dbsync-hwinfo/0
      - decoder/syscollector-dbsync-hwinfo-inserted/0
      - decoder/syscollector-dbsync-network-address/0
      - decoder/syscollector-dbsync-network-address-inserted/0
      - decoder/syscollector-dbsync-network-iface/0
      - decoder/syscollector-dbsync-network-iface-inserted/0
      - decoder/syscollector-dbsync-network-protocol-inserted/0
      - decoder/syscollector-dbsync-packages/0
      - decoder/syscollector-dbsync-packages-inserted/0
      - decoder/syscollector-hardware/0
      - decoder/syscollector-hotfix/0
      - decoder/syscollector-netinfo/0
      - decoder/syscollector-network/0
      - decoder/syscollector-network-end/0
      - decoder/syscollector-network-ip/0
      - decoder/syscollector-osinfo/0
      - decoder/syscollector-port/0
      - decoder/syscollector-port-del/0
      - decoder/syscollector-port-save/0
      - decoder/syscollector-process/0
      - decoder/syscollector-process-del/0
      - decoder/syscollector-process-save/0
      - decoder/syscollector-program/0
      - decoder/syscollector-program-del/0
      - decoder/syscollector-program-save/0
      - decoder/apache-access/0
      - decoder/syslog/0
    outputs:
      - output/file-output/0
    ```

6. Add `- event.original: <source.ip> - - [<event.created/HTTPDATE>] "<http.request.method> <url.original> HTTP/<http.version>" <http.response.status_code> <http.response.body.bytes> "-" "<user_agent.original>"` as new `parse.logpar` item

7. Update the decoder
    ```
    root@engine:/home/vagrant/engine/wazuh/src/engine# /var/ossec/engine/wazuh-engine catalog update decoder/apache-access/0 < ruleset/decoders/apache-access.yml 
    OK
    ```

8. Verify the decoder is updated
    ```
    root@engine:/home/vagrant/engine/wazuh/src/engine# /var/ossec/engine/wazuh-engine catalog get decoder/apache-access/0 | grep event.original
      - event.original: +ef_exists
        - event.original: <source.ip> - - [<event.created/HTTPDATE>] "<http.request.method> <url.original> HTTP/<http.version>" <http.response.status_code> <http.response.body.bytes>
        - event.original: <source.ip> - - [<event.created/HTTPDATE>] "<http.request.method> <url.original> HTTP/<http.version>" <http.response.status_code> <http.response.body.bytes> "-" "<user_agent.original>"
    ```

9. Verify that the decoder collect works with a sample log
    ```
    root@engine:/home/vagrant/engine/wazuh/src/engine# /var/ossec/engine/wazuh-engine test -q 1 -d


    Enter log in single line (Crtl+C to exit):

    192.168.10.1 - - [10/Jul/1992:10:07:13 +0200] "GET /someicon.ico HTTP/1.1" 404 209


    DECODERS:
      decoder/queue-sca/0  ->  failure
      decoder/queue-syslog/0  ->  failure
      decoder/queue-dbsync/0  ->  failure
      decoder/queue-rootcheck/0  ->  failure
      decoder/queue-localfile/0  ->  success
        decoder/syslog/0  ->  failure
        decoder/apache-access/0  ->  success

    RULES:


    OUTPUT:

    {
        "wazuh": {
            "queue": 49,
            "origin": "/dev/stdin"
        },
        "event": {
            "original": "192.168.10.1 - - [10/Jul/1992:10:07:13 +0200] \"GET /someicon.ico HTTP/1.1\" 404 209",
            "created": "1992-07-10T10:07:13.000Z",
            "kind": "event",
            "dataset": "apache.access",
            "category": [
                "web"
            ],
            "module": "apache",
            "outcome": "failure"
        },
        "http": {
            "response": {
                "status_code": 404,
                "body": {
                    "bytes": 209
                }
            },
            "version": "1.1",
            "request": {
                "method": "GET"
            }
        },
        "url": {
            "original": "/someicon.ico"
        },
        "source": {
            "ip": "192.168.10.1"
        },
        "service": {
            "type": "apache"
        }
    }

    ```
> we can check the decoders flow: `decoder/apache-access/0  ->  success`. Deeper trace can be generated using `-dd` instead. 

10. Check that it appears within `wazuh-alert-5.x-*` in the dashboard(In progress)
