### ISSUE TITLE
Restructure and reformat wazuh-db and analysisd tests

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-qa#422]
Hello team,

This issue aims to restructure the test and data files for analysisd and wazuh-db tests.

Actually, the yaml estructure with the test cases information is as follows:
```
---
# Check success use cases (save2, load and delete)
-
  input: "agent 001 syscheck save2 {\"path\":\"/home/test/file2\",\"timestamp\":1575421292,\"attributes\":{\"type\":\"file\",\"size\":0,\"perm\":\"rw-r--r--\",\"uid\":\"0\",\"gid\":\"0\",\"user_name\":\"root\",\"group_name\":\"root\",\"inode\":16879,\"mtime\":1575421292,\"hash_md5\":\"d41d8cd98f00b204e9800998ecf8427e\",\"hash_sha1\":\"da39a3ee5e6b4b0d3255bfef95601890afd80709\",\"hash_sha256\":\"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\",\"checksum\":\"f65b9f66c5ef257a7566b98e862732640d502b6f\"}}"
  output: "ok"
  type: "Syscheck save2 success"
-
  input: "agent 001 syscheck load /home/test/file2"
  output: "ok 0:rw-r--r--:0:0:d41d8cd98f00b204e9800998ecf8427e:da39a3ee5e6b4b0d3255bfef95601890afd80709:root:root:1575421292:16879:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855:!1:1575421292"
  type: "Syscheck save2 load success"
-
  input: "agent 001 syscheck load /home/test/file"
  output: "ok "
  type: "Syscheck save2 load success"
-
  input: "agent 001 syscheck delete /home/test/file2"
  output: "ok"
  type: "Syscheck delete success"
-
  input: "agent 001 syscheck load /home/test/file2"
  output: "ok "
  type: "Syscheck save2 load success"
```

This development should establish a new yaml estructure where every test case is comprised of  a name, description and as many stages as deemed neccesary, such as:
```
---
-
  name: "Basic success"
  description: "Check success use cases (save2, load and delete)"
  test_case:
  -
    input: "agent 001 syscheck save2 {\"path\":\"/home/test/file2\",\"timestamp\":1575421292,\"attributes\":{\"type\":\"file\",\"size\":0,\"perm\":\"rw-r--r--\",\"uid\":\"0\",\"gid\":\"0\",\"user_name\":\"root\",\"group_name\":\"root\",\"inode\":16879,\"mtime\":1575421292,\"hash_md5\":\"d41d8cd98f00b204e9800998ecf8427e\",\"hash_sha1\":\"da39a3ee5e6b4b0d3255bfef95601890afd80709\",\"hash_sha256\":\"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\",\"checksum\":\"f65b9f66c5ef257a7566b98e862732640d502b6f\"}}"
    output: "ok"
    stage: "Syscheck save2 success"
  -
    input: "agent 001 syscheck load /home/test/file3"
    output: "ok 0:rw-r--r--:0:0:d41d8cd98f00b204e9800998ecf8427e:da39a3ee5e6b4b0d3255bfef95601890afd80709:root:root:1575421292:16879:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855:!1:1575421292"
    stage: "Syscheck save2 load success"
  -
    input: "agent 001 syscheck load /home/test/file"
    output: "ok "
    stage: "Syscheck save2 load success"
  -
    input: "agent 001 syscheck delete /home/test/file2"
    output: "ok"
    stage: "Syscheck delete success"
  -
    input: "agent 001 syscheck load /home/test/file2"
    output: "ok "
    stage: "Syscheck save2 load success"
```
