### ISSUE TITLE
Agent installation fails for `one_manager_agent` role

### ISSUE THREAD

**Issue by roronoasins** [wazuh/wazuh-qa#4294]
## Description
The system tests have environments that use roles to provision docker containers. There is an environment that has a bug when installing an agent.

The `agent-role` for the `one_manager_agent` environment has a bug where the agent package download and installation is like follows:
```
- name: "Get agent package"
  ansible.builtin.get_url:
    url: "https://{{package_repository}}.wazuh.com/{{repository}}/apt/pool/main/w/wazuh-agent/wazuh-agent_{{package_version}}-{{package_revision}}_amd64.deb"
    dest: /tmp/wazuh-manager.deb
  when: wazuh_branch is not defined

- name: "Install agent package"
  ansible.builtin.apt:
    deb: /tmp/wazuh-agent.deb
  when: wazuh_branch is not defined
```

As it download the package as `/tmp/wazuh-manager.deb`. When it tries to install it, It fails because it expects `/tmp/wazuh-agent.deb`

## Tasks
- [ ] Fix package name
