### ISSUE TITLE
Agent installation fails for `manager_agent` role

### ISSUE THREAD

**Issue by roronoasins** [wazuh/wazuh-qa#4295]
## Description
The system tests have environments that use roles to provision docker containers. There is an environment that has a bug when installing an agent.

The `agent-role` for the `manager_agent` environment has a bug when copying the `ossec.conf` and registering the agents:
```
- name: Copy ossec.conf file
  copy:
    src: ../files/ossec.conf
    dest: /var/ossec/etc/ossec.conf
    owner: "{{agent_user}}"
    mode: '0664'
```
```
- name: Register agents
  lineinfile:
    path: /var/ossec/etc/client.keys
    line: "{{ agent_id }} {{agent_hostname}} any {{ agent_key }}"
    owner: "{{agent_user}}"
    mode: "0664"
    create: yes
```

The owner should be changed from `owner: "{{agent_user}}"` to `owner: 'root'`

Besides, the task that restarts the agents uses a deprecated bin:
```
fatal: [wazuh-agent1]: FAILED! => changed=false 
  cmd: /var/ossec/bin/ossec-control restart
  msg: '[Errno 2] No such file or directory'
  rc: 2
  stderr: ''
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
```

## Tasks
- [ ] Fix owner field value
