### ISSUE TITLE
DTT1 - Design and develop PoC

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-qa#4524]
EPIC: https://github.com/wazuh/wazuh-qa/issues/4495

## Description

This issue aims to design and create an initial Proof of Concept based on the analysis carried out in the issue https://github.com/wazuh/wazuh-qa/issues/4519

In this way, the PoC will show the following functionalities on a single system:

- https://github.com/wazuh/wazuh-qa/issues/4663
- https://github.com/wazuh/wazuh-qa/issues/4665
- https://github.com/wazuh/wazuh-qa/issues/4666
- https://github.com/wazuh/wazuh-qa/issues/4667
- https://github.com/wazuh/wazuh-qa/issues/4668

This PoC will have the following bases:

- Deployment of two Ubuntu 22 instances
- Installation of a Wazuh agent and manager of the latest productive version
- The tests will be executed on the Wazuh agent and manager instances
- The results will be observed through the build console
- All development can be executed locally through scripts written in Python, as well as in Jenkins through modular pipelines

The composition of the tests will be as follows:

- Install
- Registration
- Connection
- Basic info
- Restart
- Stop
- Uninstall

**Comment by rauldpm** [comment]
I have to stop working on this issue to work on an issue stopper for 4.6.0 https://github.com/wazuh/wazuh-packages/issues/2460

**Comment by rauldpm** [comment]
## Update report - Test

- Created Ansible class
  - This class will use the ansible_runner module to run playbooks using an inventory
- The main Python file will create an Ansible object and manage all the connections
- Created a playbook to deploy a Wazuh agent and a Wazuh manager in two instances following the documentation process
  - This playbook will, sequentially, configure the repositories in all nodes, install the packages, and start the services

<details><summary>Playbook execution</summary>

```
╰─➤  python3 test.py

PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
ok: [Agent1]
ok: [Manager]

TASK [Install GPG key] *********************************************************
changed: [Manager]
changed: [Agent1]

TASK [Add Wazuh repository] ****************************************************
changed: [Agent1]
changed: [Manager]

TASK [Update package information] **********************************************
changed: [Manager]
changed: [Agent1]

PLAY [Manager*] ****************************************************************

TASK [Gathering Facts] *********************************************************
ok: [Manager]

TASK [Install the Wazuh manager] ***********************************************
changed: [Manager]

TASK [Enable and start Wazuh service] ******************************************
changed: [Manager] => (item=systemctl daemon-reload)
changed: [Manager] => (item=systemctl enable wazuh-manager)
changed: [Manager] => (item=systemctl start wazuh-manager)

PLAY [Agent*] ******************************************************************

TASK [Gathering Facts] *********************************************************
ok: [Agent1]

TASK [Install the Wazuh agent with environment variables] **********************
changed: [Agent1]

TASK [Enable and start Wazuh service] ******************************************
changed: [Agent1] => (item=systemctl daemon-reload)
changed: [Agent1] => (item=systemctl enable wazuh-agent)
changed: [Agent1] => (item=systemctl start wazuh-agent)

PLAY RECAP *********************************************************************
Agent1                     : ok=7    changed=5    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
Manager                    : ok=7    changed=5    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0  
```

![image](https://github.com/wazuh/wazuh-qa/assets/14913942/e3fe5b45-8412-49b0-aad8-df8438cc5099)


</details>

**Comment by rauldpm** [comment]
## Update report

- Worked on the Wazuh agent and manager tests
- Migrated current tests to the new execution format
- Working on new sequential tests between nodes

**Comment by jnasselle** [comment]
# Update report

- Developing infrastructure provisioning script
- Approach:
 - Tool: `infra.py` 
   - Input parameters: file requesting resources. ie
   ```yaml
    ---
    - composite-name: linux-ubuntu-22.04-amd64
      role: agent
      provider: aws
      alias: Agent
    - composite-name: linux-ubuntu-22.04-amd64
      role: manager
      provider: aws
      alias: Manager
   ```
 - Specs: define what is supported by the tool
   -  Roles: Wazuh currently constrains roles based on OS resources. Defined on `specs/roles.yaml`
   ```yaml
    - role: agent
      composite-name: 
        linux-*-amd64:
          aws:
            instance-type: t2.nano
        linux-*-arm64:
          aws:
            instance-type: c7gn.medium
    - role: manager
      composite-name: 
        linux-*-amd64:
          aws:
            instance-type: c5a.xlarge
        linux-*-arm64:
          aws:
            instance-type: c6g.xlarge
   ```
   -  OS: Define OS, its provider, and ID for each one. Defined on `specs/os/*.yaml` grouped by OS family i.e ubuntu.yaml
    ```yaml
    ---
    linux-ubuntu-22.04-amd64:
      specs:
        distro: ubuntu
        familly: linux
        version: 22.04
        codename: jammy
        arch: amd64
      providers:
        aws:
          ami: ami-0fc5d935ebf8bc3bc
          zone: us-east-1
        vagrant:
          box: ubuntu/focal64
    linux-ubuntu-22.04-arm64:
      specs:
        distro: ubuntu
        familly: linux
        version: 22.04
        codename: jammy
        arch: arm64
      providers:
        aws:
          ami: ami-016485166ec7fa705
          zone: us-east-1
    ```
   -  OS: Define providers default values, used in case the were not explicitly defined.Defined on `specs/providers/*.yaml` i.e aws.yaml
     ```yaml
        security-group: [ sg-0877d224f9c5b2708 ]
        zone: us-east-1
        key: 
          type: fixed
          name: jnasselle-dev
        name:
          type: dynamic
          prefix: dt-${tier}-${os}-${arch}-${type}
        tags:
          type: qa
     ```
