### ISSUE TITLE
HostMonitor method in system tests does not detect logs correctly

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh-qa#4526]
Running tests on different EC2 instances at https://github.com/wazuh/wazuh-qa/issues/4525 has revealed that the HostMonitor method in the system tests exhibits instability. This instability is directly proportional to the performance of the EC2 instance. 

In the case of the `basic_cluster`, it results in false negatives when using `T2, T3 xlarge EC2`instances (being fixed in `C5.xlarge`), and in the `agentless_cluster`, it consistently produces a false negative even when utilizing up to a `C5.xlarge` instance.

Since this instability persists in the `agentless_cluster` with a false negative, further investigation is required.

According to the analysis of test results, the log that HostMonitor is searching for is present but is not being detected by the method.

**Comment by pro-akim** [comment]
HostMonitor takes from messages.yml the log that should check.
Messages.yaml has the following structure:

```
wazuh-master:
  - regex: '.*File too large to be synced: /var/ossec/etc/rules/test_file_too_big'
    path: "/var/ossec/logs/cluster.log"
    timeout: 60
```

In agentless_cluster test, the consistently failing test was `test_zip_size_limit `in `/test_cluster/test_integrity_sync/test_integrity_sync.py` and most of the cases it failed because it could not find the following messages:
```
wazuh-master:
  - regex: '.*File too large to be synced: /var/ossec/etc/rules/test_file_too_big'
    path: "/var/ossec/logs/cluster.log"
    timeout: 60
```

and

```
wazuh-master:
  - regex: ".*wazuh-worker1.*Files to create in worker: 1 \\| Files to update in worker: 0 \\| Files to delete in worker: 0.*"
    path: "/var/ossec/logs/cluster.log"
    timeout: 100
  - regex: ".*wazuh-worker2.*Files to create in worker: 1 \\| Files to update in worker: 0 \\| Files to delete in worker: 0.*"
    path: "/var/ossec/logs/cluster.log"
    timeout: 100
```

Changing all the timeouts to 180 the test worked fine in a EC2 Ubuntu 22.04.3 t3.large 15GB HD where this test used to failed.

Example:
Before changes:
[timeout_before_changes.zip](https://github.com/wazuh/wazuh-qa/files/12664033/timeout_returned.zip)

After changing all timeouts to 180:
[timeout_180.zip](https://github.com/wazuh/wazuh-qa/files/12664036/timeout_180.zip)
