### ISSUE TITLE
Add Vulnerability Detector System End-to-End syscollector initial scans tests

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-qa#4590]
| Target version | Related issue | Related PR/dev branch |
|-----------------------|--------------------|-----------------------------------|
|  4.8.0                 |  #4369            |                 https://github.com/wazuh/wazuh-qa/pull/4703                          |

## Description

This issue aims to create the basic End-to-end test cases defined in https://github.com/wazuh/wazuh-qa/issues/4531. As all tests defined in the issue are part of the minimal required testing suite, and as tests have tight dependencies, the cases that are part of the basis for all test cases will be done in this issue, so development can be parallelized. 

## Proposed test cases

- [x] E2E-VD-1: First syscollector scan (Rsync)
- [x] E2E-VD-2: Subsequent scan (Dbsync) without any installation
...

## Considerations

-  This development is the basis for the rest of the test cases. It should be prioritized and developed ASAP to allow  parallelization of development the rest of the tests.
- Tests must work on all proposed OSs.

**Comment by Rebits** [comment]
Found some provision errors:
- Windows 11 AMI does not include any python. This could lead into potential errors due to it is set by default a python interpreter that does actually not exist in the host. In addition, after some testing in the environment it seems that it is not possible to use some system testing tool over this Windows 11 hosts.
- macOS Agent is not correctly provisioned. More information [here](https://github.com/wazuh/wazuh-qa/issues/4581)

It has been created a basic test structure and some fixture for configure the environment.
The current E2E approach has several limitations:
- Environment validation does not work for the Vulnerability Detector proposed environment. This should be adapted or disabled by default 
- Configuration of the environment is implemented appending code block in the ossec.conf. It is difficult to implent complex configurations.

Created class method to configure the environment through YAML configurations

**Comment by Rebits** [comment]
Continue creating common fixtures for the basic tests.

**Comment by Rebits** [comment]
Created first PoC of the `E2E-VD-3` tests and common structure for all the basic tests cases

**Comment by Rebits** [comment]
|Development branch|
| --- | 
| `enhacement/4590-vd-basic-test-cases` |

There still some issues regarding the monitoring of the logs. Currently working on it

**Comment by Rebits** [comment]
|Development branch|
| --- | 
| `enhacement/4590-vd-basic-test-cases` |


The Installation of a vulnerable package case was implemented correctly. This was performed following this case structure 

```yaml
- case: "Updating a vulnerable package that remains vulnerable to the same CVE"
  id: "update_vuln_package_remain_vulnerable"
  description: "Updating a vulnerable package that remains vulnerable to the same CVE"
  preconditions:
      tasks:
        - install_package:
            package:
              centos: https://downloads.rclone.org/v1.49.5/rclone-v1.49.5-linux-amd64.rpm
              ubuntu: https://downloads.rclone.org/v1.49.5/rclone-v1.49.5-linux-amd64.deb
      check_alerts:
          centos:
            - event: install_package
              name: "rclone"
              version: "1.49.5"
          ubuntu:
              - event: install_package
                name: "rclone"
                version: "1.49.5"
  body:
    tasks:
      - install_package:
          package:
            centos: https://downloads.rclone.org/v1.50.0/rclone-v1.50.0-linux-amd64.rpm
            ubuntu: https://downloads.rclone.org/v1.50.0/rclone-v1.50.0-linux-amd64.deb
    check_alerts:
        centos:
          - event: upgrade_package
            name: "rclone"
            version: "1.50.0"
        ubuntu:
            - event: upgrade_package
              name: "rclone"
              version: "1.50.0"
  teardown:
    - remove_package:
        package:
          centos: rclone
          ubuntu: rclone
```

This approach will allow us to include desired cases easily. However this first iteration do not include dependency.
The implementation of dynamic dependency could lead into delays in the development

> **Warning**
> Currently it is only checked that the package installation/removal/upgrade alert was generated in the manager. It would be necessary a development branch to implement a fully functional tests.


### **Currently working**

- Support for Windows Endpoint
- Implementation in the rest of the tests cases
- Creation of a solid vulnerability packages repository
