### ISSUE TITLE
DTT1 - PoC - Test module

### ISSUE THREAD

**Issue by fcaffieri** [wazuh/wazuh-qa#4666]
## Description

This issue aims to design and create a PoC of the Test module.

This module is responsible for launching the test into the infrastructure allocated and provisioned. 
This module will work as a black box where it will have a clear input and output.
- Input: A YAML file with all the resources allocated and provisioned.
- output: The result of the test.

For this PoC, this module will test the following use of cases:

- [x] Install
- [x] Registration
- [x] Connection
- [x] Basic info
- [x] Restart
- [x] Stop
- [x] Uninstall

> Parent issue https://github.com/wazuh/wazuh-qa/issues/4524.

**Comment by QU3B1M** [comment]
### Update report

- Cloned repo and setup environment
- Installed dependencies and configured two VMs to use in the inventory
- Facing some problems with the connection to the VMs, actual error:
  > ```
  > fatal: [Agent1]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Load key \"/wazuh-qa/poc-tests/utils/keys\": error in libcrypto\r\nvagrant@192.168.56.13: Permission denied (publickey,password).", "unreachable": true}
  > ```

**Comment by QU3B1M** [comment]
- Completed the configuration of the environment with all the playbooks running correctly
- Add new `test_install.py` test file with some basic install validations:
    ```python
    import pwd
    import grp
    
    from pathlib import Path
    
    
    ## --- Constants ---
    
    # Paths
    WAZUH_PATH = Path("/var", "ossec")
    CONFIGURATION_PATH = Path(WAZUH_PATH, "etc")
    BINARIES_PATHS = Path(WAZUH_PATH, "bin")
    WAZUH_CONF = Path(CONFIGURATION_PATH, "ossec.conf")
    WAZUH_CONTROL = Path(BINARIES_PATHS, "wazuh-control")
    
    # Unix users and groups
    WAZUH_USER = "wazuh"
    WAZUH_GROUP = "wazuh"
    
    
    ## --- Tests ---
    
    def test_wazuh_user():
        all_users = [x[0] for x in pwd.getpwall()]
        assert WAZUH_USER in all_users, "Wazuh user not found."
    
    
    def test_wazuh_group():
        all_groups = [x[0] for x in grp.getgrall()]
        assert WAZUH_GROUP in all_groups, "Wazuh group not found."
    
    
    def test_wazuh_configuration():
        assert CONFIGURATION_PATH.exists(), "Configuration directory not found."
        assert WAZUH_CONF.exists(), "Configuration file not found."
    
    
    def test_wazuh_control():
        assert BINARIES_PATHS.exists(), "Binaries directory not found."
        assert WAZUH_CONTROL.exists(), "Wazuh control binary not found."

    ```
    > The script was tested on the agent execution with all the scenarios passing.
    > ```shellsession
    >  ============================= test session starts ==============================
    > platform linux -- Python 3.8.10, pytest-7.4.3, pluggy-1.3.0 -- /usr/bin/python3
    > cachedir: .pytest_cache
    > rootdir: /tmp/tests
    > collecting ... collected 4 items
    >
    > test_install.py::test_wazuh_user PASSED                                  [ 25%]
    > test_install.py::test_wazuh_group PASSED                                 [ 50%]
    > test_install.py::test_wazuh_configuration PASSED                         [ 75%]
    > test_install.py::test_wazuh_control PASSED                               [100%]
    > 
    > ============================== 4 passed in 0.02s ===============================
    > ```

**Comment by QU3B1M** [comment]
- Pushed changes on branch [`enhacenment/4666-dtt1-poc-test-module`](https://github.com/wazuh/wazuh-qa/tree/enhacenment/4666-dtt1-poc-test-module)
- Add `test_wazuh_daemons` case to test install
    ```python
    def test_wazuh_daemons():
        actual_daemons = utils.get_daemons_status()
    
        if utils.get_service() == "agent":
            expected_daemons = constants.AGENT_DAEMONS
        else:
            expected_daemons = constants.MANAGER_DAEMONS
    
        for daemon in expected_daemons:
            assert daemon in actual_daemons.keys(), f"{daemon} not found."
    ```
- Move constants to an independent file inside a new helpers directory
    ```python
    from pathlib import Path


    # Paths
    WAZUH_ROOT = Path("/var", "ossec")
    CONFIGURATIONS_DIR = Path(WAZUH_ROOT, "etc")
    BINARIES_DIR = Path(WAZUH_ROOT, "bin")
    WAZUH_CONF = Path(CONFIGURATIONS_DIR, "ossec.conf")
    WAZUH_CONTROL = Path(BINARIES_DIR, "wazuh-control")
    
    # Unix users and groups
    WAZUH_USER = "wazuh"
    WAZUH_GROUP = "wazuh"
    
    # Daemons
    AGENTD = 'wazuh-agentd'
    AGENTLESSD = 'wazuh-agentlessd'
    ANALYSISDD = 'wazuh-analysisd'
    APID = 'wazuh-apid'
    CLUSTERD = 'wazuh-clusterd'
    CSYSLOGD = 'wazuh-csyslogd'
    EXECD = 'wazuh-execd'
    INTEGRATORD = 'wazuh-integratord'
    MAILD = 'wazuh-maild'
    MODULESD = 'wazuh-modulesd'
    MONITORD = 'wazuh-monitord'
    LOGCOLLECTORD = 'wazuh-logcollector'
    REMOTED = 'wazuh-remoted'
    SYSCHECKD = 'wazuh-syscheckd'
    WAZUH_DBD = 'wazuh-db'
    
    AGENT_DAEMONS = [AGENTD,
                     EXECD,
                     MODULESD,
                     LOGCOLLECTORD,
                     SYSCHECKD]
    
    MANAGER_DAEMONS = [AGENTLESSD,
                       ANALYSISDD,
                       APID,
                       CLUSTERD,
                       CSYSLOGD,
                       EXECD,
                       INTEGRATORD,
                       LOGCOLLECTORD,
                       MAILD,
                       MODULESD,
                       MONITORD,
                       REMOTED,
                       SYSCHECKD,
                       WAZUH_DBD]
    ```
- Create utils.py file to store the utilities functions used in the tests
    ```python
    import subprocess
    
    from .constants import WAZUH_CONTROL
    
    
    def get_service() -> str:
        """
        Retrieves the name of the Wazuh service running on the current platform.
    
        Returns:
            str: The name of the Wazuh service.
    
        """
        control_output = subprocess.check_output([WAZUH_CONTROL, "info", "-t"], stderr=subprocess.PIPE)
        return control_output.decode('utf-8').strip()
    
    
    def get_daemons_status() -> dict:
        """
        Get the status of the Wazuh daemons.
        
        Return: 
            dict: The daemons (keys) and their status(values).
        """
        daemons_status = {}
    
        control_output = subprocess.run([WAZUH_CONTROL, "status"], stdout=subprocess.PIPE)
        control_output_decoded = control_output.stdout.decode('utf-8')
    
        for line in control_output_decoded.split('\n'):
            if "running" in line:
                daemon_name = line.split(' ')[0]
                status = line.replace(daemon_name, '').replace('.', '').lstrip()
                daemons_status[daemon_name] = status
    
        return daemons_status
    
    ```

**Comment by QU3B1M** [comment]
### Update report

- Add `file_monitor` function to utils, it helps us find a certain string on a file with a timeout _(a resumed version of the integration framework's [FileMonitor](https://github.com/wazuh/qa-integration-framework/blob/main/src/wazuh_testing/tools/monitors/file_monitor.py))_ 
  ```python
  
  def file_monitor(monitored_file: str, target_string: str, timeout: int = 30) -> None:
      encoding = get_file_encoding(monitored_file)
  
      # Check in the current file content for the string.
      with open(monitored_file, encoding=encoding) as _file:
          for line in _file:
              if target_string in line:
                  return line
  
      # Start count to set the timeout.
      start_time = time.time()
  
      # Start the file monitoring for future lines.
      with open(monitored_file, encoding=encoding) as _file:
          # Go to the end of the file.
          _file.seek(0, 2)
          while time.time() - start_time < timeout:
              current_position = _file.tell()
              line = _file.readline()
  
              if not line:
                  # No new line, wait for nex try.
                  _file.seek(current_position)
                  time.sleep(0.1)
              else:
                  # New line, check if the string matches.
                  if target_string in line:
                      return line
  
  ```
- Apply

**Comment by QU3B1M** [comment]
- Add util to execute Wauzuh binaries with args
- Add `test_basic_info` python testfile and playbook (a very simple test, could be updated)
  ```python
  import os
  
  from helpers import utils
  
  
  def test_wazuh_version():
      assert os.environ['to_version'] in utils.get_version(), "Wazuh version is not the expected."
  
  
  def test_wazuh_revision():
      assert utils.get_revision() == os.environ['revision'], "Wazuh revision is not the expected."
  
  ```
- Add `restart` provision playbook with `test_restart `playbook and python test file
  `restart.yml`
  ```yaml
  - hosts: all
    become: true
    tasks:
      - name: Restart Wazuh component
        command: "/var/ossec/bin/wazuh-control restart"
  
  ```
  `test_restart.yml`
  ```yaml
  - hosts: all
    become: true
    vars:
      path: "/tmp"
      test_directory: "tests"
      test_file: "test_restart.py"
      curl_path: /usr/bin/curl
  
    tasks:
      - name: Get Wazuh target
        shell: "/var/ossec/bin/wazuh-control info | grep -E -o 'agent|server'"
        register: target
  
      - name: Run tests on Wazuh agent
        command: "pytest {{ test_file }} --target={{ target.stdout|quote }} -v"
        args:
          chdir: "{{ path }}/{{ test_directory }}"
        when: "'Agent' in inventory_hostname"
  
      - name: Run tests on Wazuh manager
        command: "pytest {{ test_file }} --target={{ target.stdout|quote }} -v"
        args:
          chdir: "{{ path }}/{{ test_directory }}"
        when: "'Manager' in inventory_hostname"
  
  ```

**Comment by QU3B1M** [comment]
- Add util to check the service status
  ```python
  
  def get_service_status() -> str:
      """
      Get the status of the Wazuh service.
  
      Returns:
          str: The status of the Wazuh service.
      """
      if get_service() == "agent":
          service_name = "wazuh-agent"
      else:
          service_name = "wazuh-manager"
      return run_command("systemctl", ["is-active", service_name]).strip()
  ```
- Complete `test_restart` python test function
  ```python
  from helpers import utils
  from helpers.constants import DELETING_RESPONSES, RELEASING_RESOURCES, STARTED, WAZUH_LOG
  
  
  # Actual running service.
  service = utils.get_service()
  
  
  def test_release_resources_shutdown_log_raised():
      assert utils.file_monitor(WAZUH_LOG, RELEASING_RESOURCES), "Release resources log not found."
  
  
  def test_deleting_responses_shutdown_log_raised():
      assert utils.file_monitor(WAZUH_LOG, DELETING_RESPONSES), "Deleting responses log not found."
  
  
  def test_start_log_raised():
      assert utils.file_monitor(WAZUH_LOG, STARTED), "Start log not found."
  
  
  def test_service_started():
      assert utils.get_service_status() == "active", "Service is not active after restart."
  
  ```
-

**Comment by QU3B1M** [comment]
### Update report
- Improve the tests ansible playbooks. WIP

**Comment by QU3B1M** [comment]
### Update report
- Resume `influxdb` implementation facing some problems in the setup, not that easy to make it work correctly as the [pytest-influxdb](https://pypi.org/project/pytest-influxdb/) plugin's documentation is not updated. Concluded in leaving aside this implementation.
- Implement [`pytest-tinybird`](https://github.com/tinybirdco/pytest-tinybird), it seems more viable to use this solution, the implementation is easy and straight forward:
  - Create a free account in tinybird.co
  - Generate an API token
  - Update the ansible playbook with the required env variables
    ```yaml
      environment:
        TINYBIRD_URL: https://api.us-east.tinybird.co     # Depends on the region.
        TINYBIRD_DATASOURCE: <DATASOURCE_NAME>            # Will be created if not existent.
        TINYBIRD_TOKEN: <TOKEN_API>                       # Token with write permissions.
    ```  
  - Add the option `--report-to-tinybird` to the test execution
    ```yaml
      block:
        - name: Execute tests
          command: "pytest {{ test_file }}.py --target={{ target }} -vl --report-to-tinybird"
    ```
