### ISSUE TITLE
DTT1 - PoC - Observability module

### ISSUE THREAD

**Issue by fcaffieri** [wazuh/wazuh-qa#4668]
## Description

This issue aims to design and create a PoC of the Observability module.

This module is responsible for centralizing all the information related to:
- Jenkins states (metrics):
    - Memory
    - Disk
    - CPU
    - Jenkins nodes
    - Executor nodes
    - Job-status
    - Calculation of quantities of OK, failed jobs, etc.

Information exploited:
- Collector output test
- Keep a history of the tests
- Allows time tracking.
- Estimate test duration.
- See status in real time of the process.
- More accurate and faster diagnosis: it will facilitate troubleshooting.

Alerts:
- Generation of alerts, due to problems in any of the modules:
   - Anomalies in the tests
   - Failures in test failures.
   - Failures in provisioning.
   - Failures in allocations.

All this information will be presented in Grafana dashboard format.

Architecture:

![image](https://github.com/wazuh/wazuh-qa/assets/89791732/6f1d3919-4f9b-4e4c-b32c-4fcbf74940ea)

For this PoC, this module will only present metrics for the VMs, nodes and workers. It will also show metrics about the Jobs (per module) and finally logs.

> Parent issue https://github.com/wazuh/wazuh-qa/issues/4524.

**Comment by fcaffieri** [comment]
## Update

Currently the following has been implemented locally:

- VM 1:
    -Jenkins
    - Loki agent for log collection
    - Prometheus agent for collecting metrics from Jenkins and the VM.

- VM 2:
    - Grafana for data visualization and exploitation

- VM 3:
    - Prometheus to obtain metrics

- VM 4:
    - Loki for information storage


--- 

## Configurations

Jenkins: standard installation and creation of example pipelines. Loki agent installation is exposed by a specific port. Prometheus agent installation.
https://www.cherryservers.com/blog/how-to-install-jenkins-on-ubuntu-22-04

Grafana: Standard installation and configuration of data sources, at the moment they are Loki and Prometheus
https://grafana.com/docs/grafana/latest/setup-grafana/installation/debian/

Prometheus: Standard installation. The integration with Jenkins was configured using the Prometheus agent installed on the Jenkins server to obtain metrics, and the Prometheus plugin was installed in Jenkins to review what metrics it provides and how to exploit them. To integrate this, this integration was configured in Prometheus for a specific port.
https://www.cherryservers.com/blog/install-prometheus-ubuntu

```
root@prometheus:/home/vagrant# cat /etc/prometheus/prometheus.yml
# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]
  - job_name: 'jenkins'
    metrics_path: /prometheus
    scheme : http
    static_configs:
      - targets: ['172.16.1.57:8080']
  - job_name: node-jenkins # Node exporter
    static_configs:
      - targets: ['172.16.1.57:9100'] 
root@prometheus:/home/vagrant#
```

Loki agent: Standard installation. For the configuration, it was configured to raise the system logs, Jenkins logs and Logs of each job executed.
https://github.com/grafana/loki/releases
https://psujit775.medium.com/how-to-setup-loki-in-ubuntu-20-04-f7aab49910fc

Node exporter: https://prometheus.io/docs/guides/node-exporter/

Promtail:
```
root@jenkins:/home/vagrant# cat /etc/promtail/config.yml
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://172.16.1.59:3100/loki/api/v1/push

scrape_configs:
  - job_name: jenkins-job-2
    static_configs:
    - targets:
        - localhost
      labels:
        job: jenkins-jobs-2
        __path__: /var/lib/jenkins/jobs/*/builds/*/*log

  - job_name: system
    static_configs:
    - targets:
        - localhost
      labels:
        job: system-logs
        __path__: /var/log/*log

  - job_name: jenkins-jobs
    static_configs:
      - targets:
          - localhost
        labels:
          job: jenkins-jobs
          __path__: /var/lib/jenkins/jobs/test/builds/4/*log

#  - job_name: jenkins_pipelines
#    static_configs:
#      - targets:
#        - localhost
#        labels:
#          job: jenkins_pipelines
#    pipeline_stages:
#    - match:
#        expression: "^.*$"
#      pipeline_stage:
#        - decorative:
#            expr: line
root@jenkins:/home/vagrant#
```
