### ISSUE TITLE
DTT1 - Iteration 3 - Provision module - Install required dependencies on each supported OS

### ISSUE THREAD

**Issue by fcaffieri** [wazuh/wazuh-qa#4859]
> Epic: https://github.com/wazuh/wazuh-qa/issues/4852

---

## Description

The objective of this issue is to ensure the installation of dependencies on each system is correct and the version is the same across all the supported OS to execute the tests.

> A new approach of the dependencies installation will be required so the deps version can be controlled by the end user 

OS to validate:

| Operating System           | Version                | Component                          | Architectures           |
|----------------------------|------------------------|------------------------------------|-------------------------|
| RedHat                     | 7                      | agents, central components         | x86_64, aarch64         |
| RedHat                     | 8                      | agents, central components         | x86_64, aarch64         |
| RedHat                     | 9                      | agents, central components         | x86_64, aarch64         |
| CentOS                     | 7                      | agents, central components         | x86_64, aarch64         |
| CentOS                     | 8                      | agents, central components         | x86_64, aarch64         |
| Debian                     | 10                     | agents, central components         | x86_64, aarch64         |
| Debian                     | 11                     | agents, central components         | x86_64, aarch64         |
| Debian                     | 12                     | agents, central components         | x86_64, aarch64         |
| Ubuntu                     | 18                     | agents                             | x86_64, aarch64         |
| Ubuntu                     | 20                     | agents, central components         | x86_64, aarch64         |
| Ubuntu                     | 22                     | agents, central components         | x86_64, aarch64         |
| Oracle Linux               | 9                      | agents, central components         | x86_64, aarch64         |
| Amazon Linux               | 2                      | agents, central components         | x86_64, aarch64         |
| Amazon Linux               | 2023                   | agents, central components         | x86_64, aarch64         |
| openSUSE                   | 15                     | agents, central components         | x86_64, aarch64         |
| SUSE                       | 15                     | agents, central components         | x86_64, aarch64         |
| ~Fedora~                     | ~38~                     | ~agents~                             | ~x86_64, aarch64~         |
| ~Windows~                    | ~10~                     | ~agents~                             | ~x86_64, aarch64~         |
| ~Windows~                    | ~11~                     | ~agents~                             | ~x86_64, aarch64~         |
| ~Windows~                    | ~Server 2012~            | ~agents~                             | ~x86_64, aarch64~         |
| ~Windows~                    | ~Server 2012 R2~         | ~agents~                             | ~x86_64, aarch64~         |
| ~Windows~                    | ~Server 2016~            | ~agents~                             | ~x86_64, aarch64~         |
| ~Windows~                    | ~Server 2019~            | ~agents~                             | ~x86_64, aarch64~         |
| ~Windows~                    | ~Server 2022~            | ~agents~                             | ~x86_64, aarch64~         |

## Tasks

- [x] Validate that the dependencies for the OS in Vagrant work
- [ ] Validate that the dependencies for the OS in AWS work
- [x] Adapt the dependencies required by the tests for each OS

**Comment by QU3B1M** [comment]
### Update report
To correctly configure "the same" environment on each system it was decided to install _python_ from source code, and then the _python based dependencies_ (pip, venv, etc..) on top of that.

To do so, some other steps are required on the _dependencies_ playbook:
1. Install the required tools to compile python source code.
    - Redhat based:
        ```shellsession
        yum groupinstall "Development Tools"
        ```
    - Debian based:
        ```shellsession
        apt-get install build-essential
        ```
    - OpenSUSE based:
        ```shellsession
        zypper install --type pattern devel_basis
        ```
    - Alpine based:
        ```shellsession
        apk add build-base
        ```
2. Compile python source code and install it.
3. Configure the installed python interpreter as default. 
4. Install & upgrade pip alongisde the other dependencies.

**Comment by QU3B1M** [comment]
### Update report

Restructure the playbooks renaming generic to package (as that's the provisioning method)
```shellsession
```

**Comment by QU3B1M** [comment]
## On hold
This issue will remain on hold until the release testing is finished

**Comment by QU3B1M** [comment]
### Update report

The new structure seems to work properly, now I´m facing an error at the python installation from sources, punctually at the "set default python version" step
```shellsession
```

**Comment by QU3B1M** [comment]
## Update report

- Dynamic python version installation from sources is successful.
  ```shellsession
  TASK [Set default python to 3.10.11] *******************************************
  changed: [192.168.57.2] => changed=true 
    cmd: |-
      sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 1
    delta: '0:00:00.011521'
    end: '2024-03-04 12:54:24.605422'
    msg: ''
    rc: 0
    start: '2024-03-04 12:54:24.593901'
    stderr: ''
    stderr_lines: <omitted>
    stdout: 'update-alternatives: using /usr/bin/python3.10 to provide /usr/bin/python3 (python3) in auto mode'
    stdout_lines: <omitted>
  
  PLAY RECAP *********************************************************************
  192.168.57.2               : ok=9    changed=8    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
  
  [2024-03-04 09:54:25] [INFO] [43479] [ThreadPoolExecutor-0_0] [workflow_engine]: [provision-install-linux-ubuntu-22.04-amd64] Finished task in 348.77 seconds.
  ```
-   Test dependencies installation in the rest of the systems (WIP)

**Comment by QU3B1M** [comment]
## Update progess

- Fix python installation from sources, tested on Debian, CentOS and Oracle 
- Add python packages provision (install and uninstall) using pip
  > The installation of the packages could be directly using the package name or with the requirements.txt
  > A task that using the pip provision would look something like this
  ```yaml
  - task: "provision-install-{agent}"
    description: "Provision resources for the {agent} agent."
    do:
      this: process
      with:
        path: python3
        args:
          - modules/provision/main.py
          - inventory: "{working-dir}/agent-{agent}/inventory.yaml"
          - dependencies:
            - agent: "{working-dir}/agent-{agent}/inventory.yaml"
          - install:
            - component: curl
            - component: python
              type: source
              version: "{python-version}"
            - component: virtualenv  # Installation of one package.
              type: pip
            - component: deps/requirements.txt  # Installation from requirements.
              type: pip
            - component: pyyaml  # Installation of one package with version.
              type: pip
              version: 6.0.1
    depends-on:
      - "allocate-{agent}"
    foreach:
      - variable: agents-os
        as: agent
  ```
