### ISSUE TITLE
DTT1 - Iteration 3 - Allocation module - Enable custom VM creation from provider config

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-qa#4864]
> Epic #4495

## Description
This issue aims to implement the required changes to enable the scenario of creating VMs based on the specific provider configuration.
> The providers will receive a **`ProviderConfig`** object (`AWSConfig` or `VagrantConfig`)
### Tasks
- [x] Implement custom VM creation on AWS
- [x] Implement custom VM creation on Vagrant

**Comment by QU3B1M** [comment]
### Implementation on Vagrant

- Added the optional parameter `custom-provider-config` as the path for the custom config to use _(file must be yaml)_
- Enabled on the `VagrantProvider` and `Allocator` classes the option to use a custom config with the required validations

**Usage**
1. Create a .yaml file with the `VagrantConfig` values
    `test.yaml`
    ```yaml
    ip: '192.168.57.3'
    cpu: 1
    memory: 2048
    box: 'generic/ubuntu2004'
    box_version: '4.3.8'
    public_key: '/tmp/wazuh-qa/VAGRANT-1179DAFB-EFDD-47BA-B97F-5ECC8B3428B7/instance_key.pub'
    ```
2. Execute the allocator with the new parameter
    ```shellsession
    python launchers/allocation.py --provider vagrant --size small --composite-name linux-ubuntu-20.04-amd64  --custom-provider-config test.yaml
    ```
3. Check `track-output` and the created `Vagrantfile`
    ```shellsession
    cat /tmp/wazuh-qa/track.yml
    identifier: VAGRANT-A2E39E54-4EC4-48F8-AD35-64D86143625C
    instance_dir: /tmp/wazuh-qa/VAGRANT-A2E39E54-4EC4-48F8-AD35-64D86143625C
    key_path: /tmp/wazuh-qa/VAGRANT-A2E39E54-4EC4-48F8-AD35-64D86143625C/instance_key
    provider: vagrant
    ```
    `/tmp/wazuh-qa/VAGRANT-A2E39E54-4EC4-48F8-AD35-64D86143625C/Vagrantfile `
    ```Ruby
    Vagrant.configure("2") do |config|
        config.vm.box = "generic/ubuntu2004"
        config.vm.box_version = "4.3.8"
        config.vm.provision "file", source: "/tmp/wazuh-qa/VAGRANT-A2E39E54-4EC4-48F8-AD35-64D86143625C/instance_key.pub", destination: ".ssh/authorized_keys"
        config.vm.network "private_network", ip:"192.168.57.2"
        config.vm.provider "virtualbox" do |v|
            v.memory = 2048
            v.cpus = 1
        end
    end
    ```

**Comment by QU3B1M** [comment]
### Implementation on AWS

- Enabled on the `AWSProvider` class the option to use a custom config with the required validations

**Usage validation**
1. Create a .yaml file with the `AWSConfig` values
    `test.yaml`
    ```yaml
    ami: 'ami-0fc5d935ebf8bc3bc'
    zone: 'us-east-1'
    user: 'ubuntu'
    key_name: 'AA86C4DBBF5A_key'
    type: 't2.small'
    security_groups: ['sg-023fd37c4e5b679de']
    ```
2. Execute the allocator with the new parameter
    ```shellsession
    python launchers/allocation.py --provider aws --size small --composite-name linux-ubuntu-20.04-amd64  --custom-provider-config test.yaml
    ```
3. Check `track-output` and the created instance on AWS
    ```shellsession
    cat /tmp/wazuh-qa/track.yml
    identifier: i-07cfa6cca8bda9628
    instance_dir: /tmp/wazuh-qa/i-07cfa6cca8bda9628
    key_path: /tmp/wazuh-qa/i-07cfa6cca8bda9628/AA86C4DBBF5A_key.pem
    provider: aws
    ```
    ![image](https://github.com/wazuh/wazuh-qa/assets/44633633/b5524ac3-2748-4a6d-a2f8-99e4a6b05fc9)
