### ISSUE TITLE
Test install fails on MacOS arm64 with invalid server MANAGER_IP

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-qa#5079]
| Target version | Related issue | Related PR/dev branch |
|---|---|---|
| 4.8.0-beta2  | https://github.com/wazuh/wazuh/issues/22072  |  https://github.com/wazuh/wazuh/tree/v4.8.0-beta2 |

## Description

Test install for `macos-12 ARM64` is capturing an error `Invalid server address found: 'MANAGER_IP'` on the macos agent startup, we are not able to reproduce this error locally, it just happens on the jenkins executions: 
- https://ci.wazuh.info/job/Test_install/154329/console
- https://ci.wazuh.info/job/Test_install/154325/console

- <details><summary>Local reproduction</summary>
  
    
  1. Install Wazuh agent
  ```console
  sh-3.2# installer -pkg wazuh-agent-4.8.0-1.arm64.pkg -target /
  installer: Package name is Wazuh Agent
  installer: Installing at base path /
  installer: The install was successful.
  ```
  
  2. Check for errors
  ```console
  sh-3.2# cat /Library/Ossec/logs/ossec.log | grep -iE "err|warn"
  sh-3.2#
  ```
  
  3. Set manager IP address
  ```console
  sh-3.2# nano /Library/Ossec/etc/ossec.conf
  sh-3.2# grep "<address>" /Library/Ossec/etc/ossec.conf
        <address>192.168.100.150</address>
  sh-3.2#
  ```
  
  4. Restart agent
  ```console 
  sh-3.2# /Library/Ossec/bin/wazuh-control restart
  wazuh-modulesd not running...
  wazuh-logcollector not running...
  wazuh-syscheckd not running...
  wazuh-agentd not running...
  wazuh-execd not running...
  Wazuh v4.8.0 Stopped
  Starting Wazuh v4.8.0...
  Started wazuh-execd...
  Started wazuh-agentd...
  Started wazuh-syscheckd...
  Started wazuh-logcollector...
  Started wazuh-modulesd...
  Completed.
  ```
  5. Check for errors after start-up
  ```console
  sh-3.2# cat /Library/Ossec/logs/ossec.log | grep -iE "err|warn"
  sh-3.2#
  ```
  </details>

The local reproduction was tried several times, each time it resulted successful with no error ([evidence](https://github.com/wazuh/wazuh-qa/issues/5047#issuecomment-1977437774)).
It all points that the error comes from the tests side, also, there are some things we noted about the jenkins pipeline that could be useful to note 
- The agent is not being installed with the "one-line installation" nor the `WAZUH_MANAGER` var is being configured
  <details><summary>install_agent.yaml playbook</summary>
  
  ```yaml
  ---
  
  - hosts: all
    become: yes
    vars:
      build_dir: "{{ hostvars[inventory_hostname].build_dir }}"
    tasks:
  
    - name: Make new dir to store test
      file:
        path: "{{ build_dir }}"
        state: directory
  
    - name: Download the wazuh package
      get_url:
        url: "{{ package_url }}"
        dest: "{{ build_dir }}/{{ package_name }}"
        mode: 0755
        validate_certs: no
      register: download_agent_package
      retries: 6
      delay: 10
      until: download_agent_package is success
  
    - name: Install wazuh agent
      become: yes
      command: "installer -pkg {{ package_name }} -target /"
      args:
        chdir: "{{ build_dir }}"
  ```
</details>

- The registration is done in another playbook where it just replaces the MANAGER_IP with the actual IP
  <details><summary>register_agent.yaml playbook</summary>
  
  ```yaml
  ---
  
  - hosts: all
    gather_facts: no
    become: yes
    tasks:
  
    - name: Set manager IP on MacOS agent
      lineinfile:
        path: "/Library/Ossec/etc/ossec.conf"
        regexp: "<address>MANAGER_IP</address>"
        line: "<address>{{ manager_ip }}</address>"
  
    - name: Set manager port on MacOS agent
      lineinfile:
        path: "/Library/Ossec/etc/ossec.conf"
        regexp: '<port>(\d+)<\/port>'
        line: "<port>{{ manager_comm_port }}</port>"
  
    - name: Execute authd registering
      command: "/Library/Ossec/bin/agent-auth -m {{ manager_ip }} -A {{ agent_name }} "
      when:
          - manager_authd_port is undefined
          - agent_name is defined
          - version is version_compare("3.13.2", "<=")
  
    - name: Execute authd registering with a custom authd port
      command: "/Library/Ossec/bin/agent-auth -m {{ manager_ip }} -A {{ agent_name }} -p {{ manager_authd_port }}"
      when:
        - manager_authd_port is defined
        - agent_name is defined
        - version is version_compare("3.13.2", "<=")
  
    - name: Execute authd registering without agent name
      command: "/Library/Ossec/bin/agent-auth -m {{ manager_ip }}"
      when:
        - agent_name is undefined
        - manager_authd_port is undefined
        - version is version_compare("3.13.2", "<=")
  
    - name: Restart Wazuh services
      command: "/Library/Ossec/bin/wazuh-control restart"
  ```
  </details>

- In the jenkins execution, the difference on time between the ERROR and the next log message is **7 seconds**, and between the installation and registration steps execution the difference is **~25 seconds** 
    Check the execution of the Install task ( **15:18:26**) and the Register's one (**15:18:50**)
    - `install_agent.yaml`
        ```log
        [2024-02-28T15:18:26.308Z] TASK [Install wazuh agent] *****************************************************
        [2024-02-28T15:18:26.308Z] changed: [vagrant_host]
        ```
     - `register_agent.yaml`
        ```log
        [2024-02-28T15:18:50.893Z] TASK [Set manager port on MacOS agent] *****************************************
        [2024-02-28T15:18:50.894Z] changed: [vagrant_host]
        [2024-02-28T15:19:01.740Z] 
        [2024-02-28T15:19:01.741Z] TASK [Restart Wazuh services] **************************************************
        [2024-02-28T15:19:01.741Z] changed: [vagrant_host]
        ```
      
    And the times on the `ossec.log` log messages. (ERROR at **07:18:47** and INFO at **07:18:54**).
    - `ossec.log`
      ```log
      [2024-02-28T15:20:31.202Z] 2024/02/28 07:18:47 wazuh-agentd: ERROR: (4112): Invalid server address found: '
      [2024-02-28T15:20:31.202Z] 2024/02/28 07:18:47 wazuh-agentd: ERROR: (1215): No client configured. 
      [2024-02-28T15:20:31.202Z] 2024/02/28 07:18:54 wazuh-execd: INFO: Started (pid: 576).
      ``` 

> More info in the issue https://github.com/wazuh/wazuh-qa/issues/5047
## Current behavior

The agent raises an error at the startup, the test `install_agent_test.py::test_check_log_errors` fails
```shellsession
12:20:31  install_agent_test.py:91: in test_check_log_errors
12:20:31      assert expected_error == True, assert_description['error']['exception_not_detected'] + " in line {}".format(line)
12:20:31  E   AssertionError: An error was found in the log in line 2024/02/28 07:18:47 wazuh-agentd: ERROR: (4112): Invalid server address found: 'MANAGER_IP'
12:20:31  E     
12:20:31  E   assert False == True
```

## Expected results

The agent should not raise any error.
