### ISSUE TITLE
DTT1 - Test Module - Central component tests

### ISSUE THREAD

**Issue by fcaffieri** [wazuh/wazuh-qa#5219]
## Description

The objective of the issue is to make the necessary adaptations to perform connection tests on central components Wazuh indexer and Wazuh dashboard

## Tasks

- [x] Modify the way of installing the central components to use AIO
- [x] Generate Wazuh indexer connection tests
- [x] Generate Wazuh dashboard connection tests
- [x] Perform connection tests of the Wazuh indexer
- [x] Perform connection tests of the Wazuh dashboard

## Related

- Consider the following tests https://github.com/wazuh/wazuh-jenkins/tree/master/ansible-roles/stack_test

**Comment by pro-akim** [comment]
## Update
Experimenting some issues around debian 11 and 12 with dashboard install in AIO

```
root@bullseye:/home/vagrant# systemctl status wazuh-dashboard.service
Unit wazuh-dashboard.service could not be found.

```

**Comment by pro-akim** [comment]
## Update

Following tests added
- [x] Tests from https://github.com/wazuh/wazuh-jenkins/tree/master/ansible-roles/stack_test 
- [x] Port test

**Comment by pro-akim** [comment]
## Update

AWS tests :green_circle: 

<details><summary>YAML file</summary>

```
version: 0.1
description: This workflow is used to test manager deployment for DDT1 PoC
variables:
  central_components-os:
    - linux-ubuntu-20.04-amd64
    - linux-ubuntu-22.04-amd64
    - linux-amazon-2-amd64
    - linux-redhat-7-amd64
    - linux-redhat-8-amd64
    - linux-redhat-9-amd64
    - linux-centos-7-amd64
    - linux-centos-8-amd64
    - linux-debian-10-amd64
    - linux-debian-11-amd64
    - linux-debian-12-amd64
  infra-provider: aws
  working-dir: /tmp/dtt1-poc

tasks:
  # Unique central components allocate task
  - task: "allocate-central_components-{central_components}"
    description: "Allocate resources for the central_components."
    do:
      this: process
      with:
        path: python3
        args:
          - modules/allocation/main.py
          - action: create
          - provider: "{infra-provider}"
          - size: large
          - composite-name: "{central_components}"
          - inventory-output: "{working-dir}/central_components-{central_components}/inventory.yaml"
          - track-output: "{working-dir}/central_components-{central_components}/track.yaml"
          - label-termination-date: "1d"
          - label-team: "qa"
    on-error: "abort-all"
    foreach:
      - variable: central_components-os
        as: central_components
    cleanup:
      this: process
      with:
        path: python3
        args:
          - modules/allocation/main.py
          - action: delete
          - track-output: "{working-dir}/central_components-{central_components-os}/track.yaml"

  # Generic manager test task
  - task: "run-central_components-{central_components}-tests"
    description: "Run tests install for the central_components."
    do:
      this: process
      with:
        path: python3
        args:
          - modules/testing/main.py
          - targets:
            - wazuh-1: "{working-dir}/central_components-{central_components}/inventory.yaml"
          - tests: "install,restart,stop,uninstall"
          - component: "central_components"
          - wazuh-version: "4.7.3"
          - wazuh-revision: "40714"
          - live: "True"
    on-error: "abort-all"
    foreach:
      - variable: central_components-os
        as: central_components

```

</details>
