### ISSUE TITLE
Upgrade macOS package cases for Vulnerability Scanner E2E are not properly configured

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#5312]
# Description

The recent replacement of Vulnerability Detection End-to-End (E2E) test cases for the macOS agent in [PR #5174](https://github.com/wazuh/wazuh-qa/pull/5174) introduced an issue where upgrade cases lack the necessary setup steps to install the specified package, leading to test failures on macOS endpoints.

# Issue

In case such as `upgrade_package_nonvulnerable_to_vulnerable`, the goal is to confirm that the `luxon-2.5.2` version does not present any vulnerability and that the new vulnerability associated with the updated version, `luxon-3.0.0`, emerge. However, the current upgrade package structure only installs the package specified in the to field, assuming it is already present on the host system. This approach was likely implemented to avoid redundant package installations.

```yaml
- case: 'Upgrade: Non vulnerable to vulnerable package'
  id: upgrade_package_nonvulnerable_to_vulnerable
  description: |
    Upgrade to non vulnerable package to vulnerable
  body:
    operation: update_package
    package:
      from:
        centos:
          amd64: grafana-9.5.13-1
          arm64v8: grafana-9.5.13-1
        ubuntu:
          amd64: grafana-9.5.13
          arm64v8: grafana-9.5.13
        windows:
          amd64: node-v18.20.2
        macos:
          amd64: luxon-2.5.2
          arm64v8: luxon-2.5.2
      to:
        centos:
          amd64: grafana-10.0.0-1
          arm64v8: grafana-10.0.0-1
        ubuntu:
          amd64: grafana-10.0.0
          arm64v8: grafana-10.0.0
        windows:
          amd64: node-v20.5.1
        macos:
          amd64: luxon-3.0.0
          arm64v8: luxon-3.0.0
```
