### ISSUE TITLE
DTT1 - 4.8.0 adaptation

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-qa#5391]
# Description

DTT1 started its development at an early stage of 4.8.0, because it was not stable enough and there are no 4.9.0 packages, development has been done with 4.7.x packages

It is necessary to adapt the TDT1 packages to 4.8.0 to incorporate the latest functionalities and improvements, such as the connection between the Wazuh manager and the Wazuh indexer.

As 4.9.0 does not present hard changes since 4.8.0 (speaking about configuration changes), the 4.8.0 adaptation should work with 4.9.0 packages too, but, to be sure, consider the following to test 4.9.0 packages, as they are not present in pre-release and they are on an early development stage

- Generate 4.9.0 packages using the QA tools (in development)
- Move the 4.9.0 packages to the `packages-dev.wazuh.com/staging` repository
- Regenerate the RPM,RPM5,APT repository metadata using the old Packages_builder pipeline (create a 4.7.4 package for each system)
- Modify the DTT1 code to use staging instead of pre-release (note: the Wazuh installation assistant should be adapted too)

## Related

- https://github.com/wazuh/wazuh-qa/issues/4495
- Main branch: 4495-dtt1-release

# Tasks

- [ ] Adapt DTT1 to 4.8.0 features
- [ ] Desired: Test 4.9.0 packages

**Comment by fcaffieri** [comment]
### Update report

**Comment by fcaffieri** [comment]
Retaking the issue with some blocks because the pre-release repository is not 100% available due to release 4.7.5
https://wazuh-team.slack.com/archives/C02A737S5MJ/p1717073543900979?thread_ts=1717053492.730899&cid=C02A737S5MJ

**Comment by fcaffieri** [comment]
### Update report

Another problem was found in macOS VMs.

After registering the agent (up to this point the installation, registration and connection with the manager was carried out satisfactorily), a test fails to determine whether the component, in this case the agent, is active by process (validation of whether it is active by Wazuh control has already passed). )

Mistake:

```
[0;31m launchctl list | grep com.wazuh.agent[0m
[0;31m command ##########[0m
[0;31m result ####################[0;31m result ####################[0;
[0;31m {'success': False, 'output': None}[0m
[0;31m [31m[2024-05-31 13:01:35] [ERROR] TESTER: agent-macos-sonoma-14-amd64 is not active by command[0m[0m
[0;31m FAILED[0m
```

To detect if the agent process is running, use this command `launchctl list | grep com.wazuh.agent`

Validating in the raised VM it is detected that the agent was installed and registered correctly and that it is active:

```
sh-3.2# /Library/Ossec/bin/wazuh-control status
wazuh-modulesd is running...
wazuh-logcollector is running...
wazuh-syscheckd is running...
wazuh-agentd is running...
wazuh-execd is running...
sh-3.2#
```

```
sh-3.2# ps aux | grep wazuh
wazuh 2142 0.1 0.1 34172172 3508 ?? S 9:01AM 0:01.49 /Library/Ossec/bin/wazuh-agentd
```

But when executing the command used in the test it gives:

![image](https://github.com/wazuh/wazuh-qa/assets/89791732/3f62073f-1311-4592-909c-f4dc40a48cd4)


And the agent successfully registered in the manager:

```
ubuntu@ip-172-31-83-167:~$ sudo su
root@ip-172-31-83-167:/home/ubuntu# /var/ossec/bin/agent_control -l

Wazuh agent_control. List of available agents:
 ID: 000, Name: ip-172-31-83-167 (server), IP: 127.0.0.1, Active/Local
 ID: 001, Name: agent-macos-sonoma-14-amd64, IP: any, Active

List of agentless devices:

root@ip-172-31-83-167:/home/ubuntu#
```

Then the way to detect whether the process is running or not was modified and the tests were relaunched.

**Comment by fcaffieri** [comment]
Test summary:

| Test | status |
|:--:| :-- | :-- |
| Test agent Linux, macOS and Windows with provision manager | :green_circle: |
| Test agent Linux, macOS and Windows installing manager with test | :green_circle: |
| Test manager | :green_circle: |
| Test Central components | :black_circle: |

In all tests, the install, registration, basic_info, connection, restart, stop, and uninstall tests were executed

**Comment by fcaffieri** [comment]
Test summary:

| Test | status |
| :--:| :-- | 
| Test agent Linux, macOS and Windows with provision manager | :green_circle: |
| Test agent Linux, macOS and Windows installing manager with test | :green_circle: |
| Test manager | :green_circle: |
| Test Central components | :black_circle: |

In all tests, the install, registration, basic_info, connection, restart, stop, and uninstall tests were executed

**Comment by fcaffieri** [comment]
### Update report

Test status on agent testing for all systems:



Input yaml:


```
version: 0.1
description: This workflow is used to test agents deployment for DDT1 PoC
variables:
  agent-os:
    - linux-redhat-7-amd64
    - linux-redhat-7-arm64
    - linux-redhat-8-amd64
    - linux-redhat-8-arm64
    - linux-redhat-9-amd64
    - linux-redhat-9-arm64
    - linux-centos-7-amd64
    - linux-centos-7-arm64
    - linux-centos-8-amd64
    - linux-centos-8-arm64
    - linux-debian-10-amd64
    - linux-debian-10-arm64
    - linux-debian-11-amd64
    - linux-debian-11-arm64
    - linux-debian-12-amd64
    - linux-debian-12-arm64
    - linux-ubuntu-22.04-amd64
    - linux-ubuntu-22.04-arm64
    - linux-ubuntu-18.04-amd64
    - linux-ubuntu-18.04-arm64
    - linux-ubuntu-20.04-amd64
    - linux-ubuntu-20.04-arm64
    - linux-oracle-9-amd64
    - linux-amazon-2-amd64
    - linux-amazon-2-arm64
    - linux-amazon-2023-amd64
    - linux-amazon-2023-arm64

  windows-agent-os:
    - windows-desktop-10-amd64
    - windows-server-2012r2-amd64
    - windows-server-2016-amd64
    - windows-server-2019-amd64
    - windows-server-2022-amd64

  macos-agent-os:
    - macos-ventura-13-amd64
    - macos-sonoma-14-amd64

  manager-os: linux-ubuntu-22.04-amd64
  infra-provider: aws
  macos-infra-provider: vagrant
  working-dir: /tmp/dtt1-poc

tasks:
  # Unique manager allocate task
  - task: "allocate-manager-{manager-os}"
    description: "Allocate resources for the manager."
    do:
      this: process
      with:
        path: python3
        args:
          - modules/allocation/main.py
          - action: create
          - provider: "{infra-provider}"
          - size: large
          - composite-name: "{manager-os}"
          - inventory-output: "{working-dir}/manager-{manager-os}/inventory.yaml"
          - track-output: "{working-dir}/manager-{manager-os}/track.yaml"
          - label-termination-date: "1d"
          - label-team: "qa"
          - label-issue: "https://github.com/wazuh/wazuh-qa/issues/5191"
    on-error: "abort-all"
    cleanup:
      this: process
      with:
        path: python3
        args:
          - modules/allocation/main.py
          - action: delete
          - track-output: "{working-dir}/manager-{manager-os}/track.yaml"

  # Unique manager provision task
  - task: "provision-manager-{manager-os}"
    description: "Provision the manager."
    do:
      this: process
      with:
        path: python3
        args:
          - modules/provision/main.py
          - inventory: "{working-dir}/manager-{manager-os}/inventory.yaml"
          - install:
            - component: wazuh-manager
              type: assistant
              version: 4.8.0
              live: False
    depends-on:
      - "allocate-manager-{manager-os}"
    on-error: "abort-all"


  # Unique agent allocate task
  - task: "allocate-agent-{agent}"
    description: "Allocate resources for the agent."
    do:
      this: process
      with:
        path: python3
        args:
          - modules/allocation/main.py
          - action: create
          - provider: "{infra-provider}"
          - size: small
          - composite-name: "{agent}"
          - inventory-output: "{working-dir}/agent-{agent}/inventory.yaml"
          - track-output: "{working-dir}/agent-{agent}/track.yaml"
          - label-termination-date: "1d"
          - label-team: "qa"
          - label-issue: "https://github.com/wazuh/wazuh-qa/issues/5191"
    on-error: "abort-all"
    foreach:
      - variable: agent-os
        as: agent
    cleanup:
      this: process
      with:
        path: python3
        args:
          - modules/allocation/main.py
          - action: delete
          - track-output: "{working-dir}/agent-{agent}/track.yaml"


  # Generic agent test task
  - task: "run-agent-{agent}-tests"
    description: "Run tests install for the agent {agent}."
    do:
      this: process
      with:
        path: python3
        args:
          - modules/testing/main.py
          - targets:
            - wazuh-1: "{working-dir}/manager-{manager-os}/inventory.yaml"
            - agent: "{working-dir}/agent-{agent}/inventory.yaml"
          - tests: "install,registration,connection,basic_info,restart,stop,uninstall"
          - component: "agent"
          - wazuh-version: "4.8.0"
          - wazuh-revision: "40811"
          - live: False
    foreach:
      - variable: agent-os
        as: agent
    depends-on:
      - "allocate-agent-{agent}"
      - "provision-manager-{manager-os}"



  # Unique agent allocate task
  - task: "allocate-macos-agent-{agent}"
    description: "Allocate resources for the agent."
    do:
      this: process
      with:
        path: python3
        args:
          - modules/allocation/main.py
          - action: create
          - provider: "{macos-infra-provider}"
          - size: small
          - composite-name: "{agent}"
          - inventory-output: "{working-dir}/agent-{agent}/inventory.yaml"
          - track-output: "{working-dir}/agent-{agent}/track.yaml"
          - label-termination-date: "1d"
          - label-team: "qa"
          - label-issue: "https://github.com/wazuh/wazuh-qa/issues/5191"
    on-error: "abort-all"
    foreach:
      - variable: macos-agent-os
        as: agent
    cleanup:
      this: process
      with:
        path: python3
        args:
          - modules/allocation/main.py
          - action: delete
          - track-output: "{working-dir}/agent-{agent}/track.yaml"


  # Generic agent test task
  - task: "run-macos-agent-{agent}-tests"
    description: "Run tests install for the agent {agent}."
    do:
      this: process
      with:
        path: python3
        args:
          - modules/testing/main.py
          - targets:
            - wazuh-1: "{working-dir}/manager-{manager-os}/inventory.yaml"
            - agent: "{working-dir}/agent-{agent}/inventory.yaml"
          - tests: "install,registration,connection,basic_info,restart,stop,uninstall"
          - component: "agent"
          - wazuh-version: "4.8.0"
          - wazuh-revision: "40811"
          - live: False
    foreach:
      - variable: macos-agent-os
        as: agent
    depends-on:
      - "allocate-macos-agent-{agent}"
      - "provision-manager-{manager-os}"


  # Unique agent allocate task
  - task: "allocate-windows-agent-{agent}"
    description: "Allocate resources for the agent."
    do:
      this: process
      with:
        path: python3
        args:
          - modules/allocation/main.py
          - action: create
          - provider: "{infra-provider}"
          - size: small
          - composite-name: "{agent}"
          - inventory-output: "{working-dir}/agent-{agent}/inventory.yaml"
          - track-output: "{working-dir}/agent-{agent}/track.yaml"
          - label-termination-date: "1d"
          - label-team: "qa"
          - label-issue: "https://github.com/wazuh/wazuh-qa/issues/5191"
    on-error: "abort-all"
    foreach:
      - variable: windows-agent-os
        as: agent
    cleanup:
      this: process
      with:
        path: python3
        args:
          - modules/allocation/main.py
          - action: delete
          - track-output: "{working-dir}/agent-{agent}/track.yaml"


  # Generic agent test task
  - task: "run-windows-agent-{agent}-tests"
    description: "Run tests install for the agent {agent}."
    do:
      this: process
      with:
        path: python3
        args:
          - modules/testing/main.py
          - targets:
            - wazuh-1: "{working-dir}/manager-{manager-os}/inventory.yaml"
            - agent: "{working-dir}/agent-{agent}/inventory.yaml"
          - tests: "install,registration,connection,basic_info,restart,stop,uninstall"
          - component: "agent"
          - wazuh-version: "4.8.0"
          - wazuh-revision: "40811"
          - live: False
    foreach:
      - variable: windows-agent-os
        as: agent
    depends-on:
      - "allocate-windows-agent-{agent}"
      - "provision-manager-{manager-os}"

```


Full Log: 

[Test-agents-complete.log](https://github.com/user-attachments/files/15551867/Test-agents-complete.log)



Summury Result: 

| Agent | Test result | Error |
| :- | :-: | :- |
| linux-redhat-7-amd64 | :green_circle: | - |
| linux-redhat-7-arm64 | :green_circle: | - |
| linux-redhat-8-amd64 | :green_circle: | - |
| linux-redhat-8-arm64 | :green_circle: | - |
| linux-redhat-9-amd64 | :green_circle: | - |
| linux-redhat-9-arm64 | :green_circle: | - |
| linux-centos-7-amd64 | :green_circle: | - |
| linux-centos-7-arm64 | :green_circle: | - |
| linux-centos-8-amd64 | :green_circle: | - |
| linux-centos-8-arm64 | :green_circle: | - |
| linux-debian-10-amd64 | :green_circle: | - |
| linux-debian-10-arm64 | :green_circle: | - |
| linux-debian-11-amd64 | :green_circle: | - |
| linux-debian-11-arm64 | :green_circle: | - |
| linux-debian-12-amd64 | :green_circle: | - |
| linux-debian-12-arm64 | :green_circle: | - |
| linux-ubuntu-22.04-amd64 | :green_circle: | - |
| linux-ubuntu-22.04-arm64 | :green_circle: | - |
| linux-ubuntu-18.04-amd64 | :green_circle: | - |
| linux-ubuntu-18.04-arm64 | :green_circle: | - |
| linux-ubuntu-20.04-amd64 | :green_circle: | - |
| linux-ubuntu-20.04-arm64 | :green_circle: | - |
| linux-oracle-9-amd64 | :green_circle: | - |
| linux-amazon-2-amd64 | :green_circle: | - |
| linux-amazon-2-arm64 | :green_circle: | - |
| linux-amazon-2023-amd64 | :green_circle: | - |
| linux-amazon-2023-arm64  | :green_circle: | - |
| windows-server-2022-amd64 | :red_circle: | test_stop.py::test_processes - Failed |
| windows-server-2012r2-amd64 | :gree_circle: | - |
| windows-server-2016-amd64 | :gree_circle: | - |
| windows-server-2019-amd64 | :gree_circle: | - |
| windows-desktop-10-amd64 | :red_circle: | Failure in time out to reach -  TESTER: Error on attempt 10 of 10: HTTPSConnectionPool|
| macos-ventura-13-amd64 | :green_cirlce | - |
| macos-ventura-13-arm64 | :black_cirlce |  |
| macos-sonoma-14-amd64 | :green_cirlce | - |
| macos-sonoma-14-arm64 | :black_cirlce |  |

**Comment by fcaffieri** [comment]
## Test macOS arm64 (WIP)

**Comment by fcaffieri** [comment]
## Test Managers

**Comment by fcaffieri** [comment]
## Research Test Manager's errors

- `linux-amazon-2-amd64`:

After intense research, it was detected that the Amazon Linux 2 problem is due to a disk space problem. When you try to download the Wazuh dashboard package, you run out of space.

Mistake:

```
23:57:43 INFO: Starting Wazuh dashboard installation.04/06/2024 23:57:50 ERROR: Wazuh dashboard installation failed.
```

In the machine:

```
Error downloading packages:
 wazuh-dashboard-4.8.0-1.x86_64: Out of space in download directory /var/cache/yum/x86_64/2/wazuh/packages
 * free 39M
 *necessary 275M

05/06/2024 15:47:00 ERROR: Wazuh dashboard installation failed.
```

The following issue was generated to fix the problem of disk space allocation by the allocator:

https://github.com/wazuh/wazuh-qa/issues/5464

- `linux-centos-8-amd64`:

After intense research, it was detected that the CentOS 8 problem is due to a problem with the CentOS 8 AppStream.

Mistake:

```
CentOS Stream 8 - AppStream 1.6 kB/s | 38 B 00:00
Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
```

The following issue was generated to fix the problem by generating a new AMI:

https://github.com/wazuh/wazuh-qa/issues/5463

### Test summary:


| Agent | Test result | Error |
| :- | :-: | :- |
| linux-amazon-2-amd64 | :red_circle: | Disk space problem |
| linux-centos-8-amd64 | :red_circle: | Wrong AMI |

**Comment by fcaffieri** [comment]
## Test Central Components:

### Test summary:

| Agent | Test result | Error |
| :- | :-: | :- |
| linux-ubuntu-20.04-amd64 | :green_circle | - |
| linux-ubuntu-22.04-amd64 | :green_circle | - |
| linux-amazon-2-amd64 | :red_circle | Disk problem |
| linux-redhat-7-amd64 | :green_circle | - |
| linux-redhat-8-amd64 | :green_circle | - |
| linux-redhat-9-amd64 | :green_circle | - |
| linux-centos-7-amd64 | :green_circle | - |
| linux-centos-8-amd64 | :red_circle | AMI problem |
| linux-debian-10-amd64 | :red_circle | Disk problem |
| linux-debian-11-amd64 | :red_circle | Disk problem |
| linux-debian-12-amd64 | :red_circle | Disk problem |

In the failed central components tests, the same problems reported for the managets tests were found.
They should be resolved with the following issues:
- https://github.com/wazuh/wazuh-qa/issues/5463
- https://github.com/wazuh/wazuh-qa/issues/5464

**Comment by fcaffieri** [comment]
## New test Central Components for operating systems that failed:

### Test summary:

| Agent | Test result | Error |
| :- | :-: | :- |
| linux-amazon-2-amd64 | :green_circle: | - |
| linux-centos-8-amd64 | :green_circle: | - |
| linux-debian-10-amd64 | :green_circle: | - |
| linux-debian-11-amd64 | :green_circle: | - |
| linux-debian-12-amd64 | :green_circle: | - |

Logs:

Amazon-2:

[Test-CC-amazon2.log](https://github.com/user-attachments/files/15744350/Test-CC-amazon2.log)


Debian:

[Test-CC-debian.log](https://github.com/user-attachments/files/15744352/Test-CC-debian.log)

CentOS 8:

[Test-CC-centos8.log](https://github.com/user-attachments/files/15744354/Test-CC-centos8.log)

**Comment by fcaffieri** [comment]
## New test Managers' for operating systems that failed:

### Test summary:

| Agent | Test result | Error |
| :- | :-: | :- |
| linux-amazon-2-amd64 | :green_circle: | - |
| linux-centos-8-amd64 | :green_circle: | - |

Logs:

[Test-manager-complete.log](https://github.com/user-attachments/files/15744364/Test-manager-complete.log)

**Comment by fcaffieri** [comment]
### Update status

After talking with @rauldpm it was decided to analyze the possibility of adding connection tests between Wazuh manager and indexer

**Comment by fcaffieri** [comment]
### Update report

Modifications were made, connection test was implemented between the Wazuh manager and indexer

Tests:

![image](https://github.com/wazuh/wazuh-qa/assets/89791732/0a9deea3-e310-49bb-bd56-b823d3969c81)


| Agent | Test result | 
| :- | :-: | 
| linux-ubuntu-20.04-amd64 | :green_circle: | 
| linux-ubuntu-22.04-amd64 | :green_circle: | 
| linux-amazon-2-amd64 | :green_circle: | 
| linux-redhat-7-amd64 | :green_circle: | 
| linux-redhat-8-amd64 | :green_circle: | 
| linux-redhat-9-amd64 | :green_circle: | 
| linux-centos-7-amd64 | :green_circle: | 
| linux-centos-8-amd64 | :green_circle: | 
| linux-debian-10-amd64 | :green_circle: | 
| linux-debian-11-amd64 | :green_circle: | 
| linux-debian-12-amd64 | :green_circle: | 

<details>

<summary>Input yaml: </summary>


```
version: 0.1
description: This workflow is used to test the Wazuh manager deployment for DDT1 PoC
variables:
  central_components-os:
    - linux-ubuntu-20.04-amd64
    - linux-ubuntu-22.04-amd64
    - linux-amazon-2-amd64
    - linux-redhat-7-amd64
    - linux-redhat-8-amd64
    - linux-redhat-9-amd64
    - linux-centos-7-amd64
    - linux-centos-8-amd64
    - linux-debian-10-amd64
    - linux-debian-11-amd64
    - linux-debian-12-amd64
  infra-provider: aws
  working-dir: /tmp/dtt1-poc

tasks:
  # Unique central components allocate task
  - task: "allocate-central_components-{central_components}"
    description: "Allocate resources for the central_components."
    do:
      this: process
      with:
        path: python3
        args:
          - modules/allocation/main.py
          - action: create
          - provider: "{infra-provider}"
          - size: large
          - composite-name: "{central_components}"
          - inventory-output: "{working-dir}/central_components-{central_components}/inventory.yaml"
          - track-output: "{working-dir}/central_components-{central_components}/track.yaml"
          - label-termination-date: "1d"
          - label-team: "qa"
    on-error: "abort-all"
    foreach:
      - variable: central_components-os
        as: central_components
    cleanup:
      this: process
      with:
        path: python3
        args:
          - modules/allocation/main.py
          - action: delete
          - track-output: "{working-dir}/central_components-{central_components-os}/track.yaml"

  # Generic manager test task
  - task: "run-central_components-{central_components}-tests"
    description: "Run tests install for the central_components."
    do:
      this: process
      with:
        path: python3
        args:
          - modules/testing/main.py
          - targets:
            - wazuh-1: "{working-dir}/central_components-{central_components}/inventory.yaml"
          - tests: "install,restart,stop,uninstall"
          - component: "central_components"
          - wazuh-version: "4.8.0"
          - wazuh-revision: "40812"
          - live: False
    on-error: "abort-all"
    foreach:
      - variable: central_components-os
        as: central_components

```

</details>


Full Log: 

[Test-CC-complete.log](https://github.com/user-attachments/files/15787987/Test-CC-complete.log)
