### ISSUE TITLE
Jobflow must allow generating multiple instances of the same type in a single execution

### ISSUE THREAD

**Issue by fcaffieri** [wazuh/wazuh-qa#5796]
| Version | Revision | Production/Development | Component | Install type | 
|:--:|:--:|:--:|:--:|:--:|
| NA   | NA   |  Development  | Jobflow   | NA |  

## Description

Jobflow is required to be able to execute the allocator in such a way that it allows more than one VM to be instantiated.
For example: 

``` 
version: 0.1
description: This workflow is used to test agents deployment for DDT1 PoC
variables:
  agent-os:
    - linux-ubuntu-24.04-amd64
    - linux-ubuntu-24.04-amd64
    - linux-ubuntu-24.04-amd64
  infra-provider: aws
  macos-infra-provider: vagrant
  working-dir: /tmp/dtt1-poc

tasks:
  # Unique agent allocate task
  - task: "allocate-agent-{agent}"
    description: "Allocate resources for the agent."
    do:
      this: process
      with:
        path: python3
        args:
          - modules/allocation/main.py
          - action: create
          - provider: "{infra-provider}"
          - size: small
          - composite-name: "{agent}"
          - instance-name: "{agent}-1"
          - inventory-output: "{working-dir}/agent-{agent}-1/inventory.yaml"
          - track-output: "{working-dir}/agent-{agent}-1/track.yaml"
          - label-termination-date: "1d"
          - label-team: "qa"
          - label-issue: "https://github.com/wazuh/wazuh/issues/26002"
    foreach:
      - variable: agent-os
        as: agent

``` 

Should allow 3 ubuntu24 to be raised.

### Evironment

| Node | Vagrant/AWS | Image | CPU | RAM (GB) | Disk size (GB) | Packages/Repository/Sources branch|
|:--:|:--:|:--:|:--:|:--:|:--:|---|
| NA | NA | NA|NA |NA | NA | NA|

### Steps to reproduce

1. Ejecute Jobflow with this yaml:

``` 
version: 0.1
description: This workflow is used to test agents deployment for DDT1 PoC
variables:
  agent-os:
    - linux-ubuntu-24.04-amd64
    - linux-ubuntu-24.04-amd64
    - linux-ubuntu-24.04-amd64
  infra-provider: aws
  macos-infra-provider: vagrant
  working-dir: /tmp/dtt1-poc

tasks:
  # Unique agent allocate task
  - task: "allocate-agent-{agent}"
    description: "Allocate resources for the agent."
    do:
      this: process
      with:
        path: python3
        args:
          - modules/allocation/main.py
          - action: create
          - provider: "{infra-provider}"
          - size: small
          - composite-name: "{agent}"
          - instance-name: "{agent}-1"
          - inventory-output: "{working-dir}/agent-{agent}-1/inventory.yaml"
          - track-output: "{working-dir}/agent-{agent}-1/track.yaml"
          - label-termination-date: "1d"
          - label-team: "qa"
          - label-issue: "https://github.com/wazuh/wazuh/issues/26002"
    foreach:
      - variable: agent-os
        as: agent

``` 

### Current result

Currently it throws the following error:

```
$ python3 -m jobflow modules/jobflow/examples/4.9.1/install/test_agents1.yaml --log-level DEBUG --threads 4 
[2024-10-02 18:31:15] [DEBUG] [1191430] [MainThread] [jobflow]: Validating input file: modules/jobflow/examples/4.9.1/install/test_agents1.yaml
[2024-10-02 18:31:15] [DEBUG] [1191430] [MainThread] [jobflow]: Loading schema file: /home/fcaffieri/repos/wazuh-qa/.venv/lib/python3.10/site-packages/jobflow/schemas/schema_v1.json
[2024-10-02 18:31:15] [DEBUG] [1191430] [MainThread] [jobflow]: Loading yaml file: modules/jobflow/examples/4.9.1/install/test_agents1.yaml
[2024-10-02 18:31:15] [DEBUG] [1191430] [MainThread] [jobflow]: Loading workflow file: modules/jobflow/examples/4.9.1/install/test_agents1.yaml
[2024-10-02 18:31:15] [DEBUG] [1191430] [MainThread] [jobflow]: Process workflow.
Error executing workflow: Duplicated task names: allocate-agent-linux-ubuntu-24.04-amd64
$ 
```

### Expected result

It is expected to instantiate the 3 VMs

### Attachments

NA

- Build link: NA

- Build parameters: python3 -m jobflow modules/jobflow/examples/4.9.1/install/test_agents1.yaml --log-level DEBUG --threads 4 

- Artifacts: .yaml

- Logs: .txt, .log or .zip

**Comment by rauldpm** [comment]
Please open an issue to the @wazuh/devel-devops team to allow the Allocator to deploy multiple instances of the same system and version

Block this issue by that issue (third party + note)

**Comment by fcaffieri** [comment]
New issue https://github.com/wazuh/wazuh-automation/issues/1874

**Comment by Rebits** [comment]
This issue will be resolved following [Redesign allocation, provisioning, and testing modules](https://github.com/wazuh/wazuh-qa-automation/issues/214).

### Overview

Currently, jobflows serve as the final launchable templates, requiring extensive modifications to set up necessary variables such as credentials, versions, and other configurations. To streamline this, an additional layer of abstraction is proposed.

The new approach separates test definitions into a template and a test set. The template generates the final jobflow, while the test set specifies the tests, typically developed in pytest or similar frameworks. This design allows the test logic to remain in the tests themselves, while the jobflow, structured as a DAG, includes deployment, provisioning, and test execution tasks.

A new tool, tentatively called launcher, will decouple provisioning and deployment from the tests themselves.

This approach aims to abstract not only the provisioning from the tests but also the template creation within jobflows. Here’s an example to illustrate:
```yaml
version: 0.1
description: This workflow is used to test agent deployments for DDT.

{% set TESTS_DIR = TESTS_DIR -%}
{%- set SERVER_OS = SERVER_OS -%}

{% set environment = [
  {
    "type": "list",
    "group": "generic",
    "hosts": AGENT_OS
  },
  {
    "type": "list",
    "group": "server",
    "hosts": [SERVER_OS]
  }
] %}

# Environment {{ environment }}

variables:
  tests-dir: {{ TESTS_DIR }}
  agent-os: {{ AGENT_OS }}

tasks:

{% include 'agent_manager_packages/agent_manager_packages.j2' %}

{%- for agent in AGENT_OS %}

  {% set counter = loop.index | string %}
  {% set agentname = agent + '-' + counter -%}
  {% set managername = SERVER_OS + '-' + 1 | string -%}

  - task: "run-{{agentname}}-tests"
    description: "Run installation tests for agent {{agent}}."
    do:
      this: process
      with:
        path: testing
        args:
          - tests-dir: "{tests-dir}"
          - targets:
            - wazuh-1: "{{WORKING_DIR}}/server-{{SERVER_OS}}/inventory.yaml"
            - agent: "{{WORKING_DIR}}/generic-{{agent}}/inventory.yaml"
          - tests: "install,registration,connection,basic_info,restart,stop,uninstall"
          - component: "agent"
          - wazuh-version: "{{VERSION}}"
          - wazuh-revision: "{{REVISION}}"
          - live: False
    depends-on:
      - "allocate-generic-{{agentname}}"
      - "install-testing-tool"
      - "provision-server-{{managername}}"

{%- endfor %}

```
In this example, instances are provisioned and deployed through the agent_manager_packages template.

With this abstraction, deploying multiple instances with the same OS is achievable using a single template. The example below shows two potential environments:


```jinja2
{% set environment1 = [
  {
    "type": "list",
    "group": "generic",
    "hosts": ['linux-ubuntu-24.04-amd64', 'linux-ubuntu-24.04-amd64']
  },
  {
    "type": "list",
    "group": "server",
    "hosts": ['linux-ubuntu-24.04-amd64', 'linux-ubuntu-24.04-amd64']
  }
] %}

{% set environment2 = [
    {
      "type": "single",
      "hostname": "testing",
      "groups": ["server"],
      "os": "linux-ubuntu-24.04-amd64",
      "size": "small",
      "number": 2
    }
  ]
%}
```

- In environment1, two linux-ubuntu-24.04-amd64 instances are deployed with names linux-ubuntu-24.04-amd64-{INSTANCE-NUMBER}.
- In environment2, two linux-ubuntu-24.04-amd64 instances are deployed with the hostname testing-{INSTANCE_NUMBER}.


Example output
```yaml
...
  - task: "allocate-generic-linux-redhat-7-amd64-1"
    description: "Allocate resources for linux-redhat-7-amd64-1"
    do:
      this: process
      with:
        path: python3
        args:
          - "/tmp/launcher-poc-20241029155334/wazuh-automation/deployability/modules/allocation/main.py"
          - action: create
          - provider: aws
          - size: litle
          - composite-name: linux-redhat-7-amd64-1
          - inventory-output: "/tmp/launcher-poc-20241029155334/generic-linux-redhat-7-amd64-1/inventory.yaml"
          - track-output: "/tmp/launcher-poc-20241029155334/generic-linux-redhat-7-amd64-1/track.yaml"
          - label-termination-date: "1d"
          - label-team: "qa"
          - label-issue: testing
    on-error: "abort-all"
    cleanup:
      this: process
      with:
        path: python3
        args:
          - /tmp/launcher-poc-20241029155334/wazuh-automation/deployability/modules/allocation/main.py
          - action: delete
          - track-output: "/tmp/launcher-poc-20241029155334/generic-linux-redhat-7-amd64-1/track.yaml"
    depends-on:
      - "allocator-ready"
    
      

  - task: "allocate-generic-linux-redhat-7-amd64-2"
    description: "Allocate resources for linux-redhat-7-amd64-2"
    do:
      this: process
      with:
        path: python3
        args:
          - "/tmp/launcher-poc-20241029155334/wazuh-automation/deployability/modules/allocation/main.py"
          - action: create
          - provider: aws
          - size: litle
          - composite-name: linux-redhat-7-amd64-2
          - inventory-output: "/tmp/launcher-poc-20241029155334/generic-linux-redhat-7-amd64-2/inventory.yaml"
          - track-output: "/tmp/launcher-poc-20241029155334/generic-linux-redhat-7-amd64-2/track.yaml"
          - label-termination-date: "1d"
          - label-team: "qa"
          - label-issue: testing
    on-error: "abort-all"
    cleanup:
      this: process
      with:
        path: python3
        args:
          - /tmp/launcher-poc-20241029155334wazuh-automation/deployability/modules/allocation/main.py
          - action: delete
          - track-output: "/tmp/launcher-poc-20241029155334/generic-linux-redhat-7-amd64-2/track.yaml"
    depends-on:
      - "allocator-ready"
...
```
