### ISSUE TITLE
Publish release 4.9.1

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#5816]
## Description
This issue attempts to track the steps necessary to publish packages, OVA, AMI and puppet forge for 4.9.1.

## Tasks
- [x] Create manual production backup.
- [x] Send AMI to analysis.
- [x] Copy files from pre-release to production
    - [x] Clone the wazuh-jenkins repository and checkout to the `v4.9.1` tag.
    - [x] Follow the steps of the README file located at `new-jenkins/procedure/publish_release/README.md` (Container of `release_tool`)
        - Check if Filebeat should be published: Not necessary
        - Use the recipe `recipes/staging-to-prod.yaml`
        - Make sure that the YAML has the correct `global-variables`
- [x] Publish unattended and templates. https://ci.wazuh.info/job/publish_unattended/347/
- [x] Publish Puppet forge. https://ci.wazuh.info/job/Publish_release/410/

**Comment by Rebits** [comment]
- **Create manual production backup**:  Used pipeline for better tracking https://ci.wazuh.info/job/Publish_release/407 :green_circle: 
-  **Send AMI to analysis**: Sent and approved :green_circle:   
  
***

~Blocked due to retag in dashboard https://github.com/wazuh/wazuh-dashboard/issues/359~ 
-  **Copy files from pre-release to production** :construction: :  In progress


**Global variables validated by**:
- [x] @juliamagan 

<details>

<summary> staging-to-prod.yaml global variables</summary>

```yaml
description: Deploy files from STAGING to PROD
global-variables:
  major: "4"
  minor: "9"
  patch: "1"
  revision: "1"
  wazuh-version: "4.9.1"
  filebeat-version: "0.4"
  global-acl: "public-read"
  from: "staging"
  to: "prod" 
  workspace: "4.x"
... 
```

</details> 


In addition, it was validated dry mode output.


I am currently working on some errors detected during some package releases. Only a part of the release was successful. Release currently in process by @rauldpm (check https://github.com/wazuh/wazuh-qa/issues/5816#issuecomment-2419296663).
Notice to @wazuh-devel-devops regarding founds errors
