### ISSUE TITLE
Package wazuh_testing: Generate an xml inner node with both elements and attributes

### ISSUE THREAD

**Issue by xr09** [wazuh/wazuh-qa#688]
# wazuh_testing

The function `set_section_wazuh_conf` does not takes into account an inner node with both elements and attributes.

A configuration like this:

```yaml
- tags:
  - test_canonical_provider
  apply_to_modules:
  - test_enabled
  sections:
  - section: vulnerability-detector
    elements:
    - enabled:
        value: 'yes'
    - interval:
        value: '5m'
    - ignore_time:
        value: '6h'
    - run_on_start:
        value: 'yes'
    - provider:
        elements:
        - enabled:
            value: 'yes'
        - os:
            value: 'bionic'
        attributes:
        - name: 'canonical'
```

Generates this config:

```xml
<vulnerability-detector>
  <enabled>yes</enabled>
  <interval>5m</interval>
  <ignore_time>6h</ignore_time>
  <run_on_start>yes</run_on_start>
  <provider>
    <enabled>yes</enabled>
    <os>bionic</os>
  </provider>
</vulnerability-detector>
```

Note the missing `name=canonical` attribute on provider.

The expected config would be this:

```xml
<vulnerability-detector>
  <enabled>yes</enabled>
  <interval>5m</interval>
  <ignore_time>6h</ignore_time>
  <run_on_start>yes</run_on_start>
  <provider name="canonical">
    <enabled>yes</enabled>
    <os>bionic</os>
  </provider>
</vulnerability-detector>
```
