### ISSUE TITLE
IT Wazuh-logtest - Check load of rules and decoders.

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh-qa#836]
Hello team!

To test Wazuh-logtest you can treat loaded multiples rules and decoders, send logs to `/var/ossec/queue/ossec` and check response is correct.

Best regards,
Juan Cabrera

**Comment by JcabreraC** [comment]
## Input/Output

**invalid token (invalid length)**

input
```
{"token": "kTy234Sdvtp7","event": "Jun 24 11:54:19 Master systemd[2099]: Started VTE child process 20118 launched by terminator process 17756.","log_format": "syslog","location": "master->/var/log/syslog"}
```

JSON expected:
```
{"token":"411964d2","message":["WARNING: (7309): 'kTy234Sdvtp7' is not a valid token","INFO: (7202): '411964d2' New token"],"codemsg":1, "output": "--JSON PROCCESS EVENT --"}
```

**Null Token**

input
```
{"token": null,"event": "Jun 24 11:54:19 Master systemd[2099]: Started VTE child process 20118 launched by terminator process 17756.","log_format": "syslog","location": "master->/var/log/syslog"}
```

JSON expected:
```
{"token":"4885bbf4","message":["INFO: (7202): '4885bbf4' New token","codemsg":0,"output": "--JSON PROCCESS EVENT --"}
```

**Missing token**

input
```
{"event": "Jun 24 11:54:19 Master systemd[2099]: Started VTE child process 20118 launched by terminator process 17756.","log_format": "syslog","location": "master->/var/log/syslog"}
```

JSON expected:
```
{"token":"4885bbf4","message":["INFO: (7202): '4885bbf4' New token","codemsg":0,"output": "--JSON PROCCESS EVENT --"}
```

**Active session**

input
```
{"token": "4885bbf4","event": "Jun 24 11:54:19 Master systemd[2099]: Started VTE child process 20118 launched by terminator process 17756.","log_format": "syslog","location": "master->/var/log/syslog"}
```

JSON expected:
```
{"token":"4885bbf4","codemsg":0,"output": "--JSON PROCCESS EVENT --"}
```

## file .yaml
``` yaml
-
  name: "Invalid token (invalid length)"
  description: "Check invalid input for client request"
  test_case:
  -
    input: '{"token": "kTy234Sdvtp7","event": "Jun 24 11:54:19 Master systemd[2099]: Started VTE child process 20118 launched by terminator process 17756.","log_format": "syslog","location": "master->/var/log/syslog"}'
    output: "{\"token\":\"411964d2\",\"messages\":[\"WARNING: (7309): 'kTy234Sdvtp7' is not a valid token\",\"INFO: (7202): '411964d2' New token\"],\"codemsg\":1, \"output\": \"--JSON PROCCESS EVENT --\"}"
    stage: 'Invalid token (invalid length)'
-
  name: "Null Token"
  description: "Check invalid input for client request"
  test_case:
  -
    input: '{"token": null,"event": "Jun 24 11:54:19 Master systemd[2099]: Started VTE child process 20118 launched by terminator process 17756.","log_format": "syslog","location": "master->/var/log/syslog"}'
    output: "{\"token\":\"4885bbf4\",\"messages\":[\"INFO: (7202): '4885bbf4' New token\",\"codemsg\":0,\"output\": \"--JSON PROCCESS EVENT --\"}"
    stage: 'Null Token'
-
  name: "Missing token"
  description: "Check invalid input for client request"
  test_case:
  -
    input: '{"event": "Jun 24 11:54:19 Master systemd[2099]: Started VTE child process 20118 launched by terminator process 17756.","log_format": "syslog","location": "master->/var/log/syslog"}'
    output: "{\"token\":\"4885bbf4\",\"messages\":[\"INFO: (7202): '4885bbf4' New token\",\"codemsg\":0,\"output\": \"--JSON PROCCESS EVENT --\"}"
    stage: 'Missing token'
-
  name: "Active session"
  description: "Check invalid input for client request"
  test_case:
  -
    input: '{"token": "4885bbf4","event": "Jun 24 11:54:19 Master systemd[2099]: Started VTE child process 20118 launched by terminator process 17756.","log_format": "syslog","location": "master->/var/log/syslog"}'
    output: '{"token":"4885bbf4","codemsg":0,"output": "--JSON PROCCESS EVENT --"}'
    stage: 'Active session'
```
