### ISSUE TITLE
Add new test template that match testing criteria

### ISSUE THREAD

**Issue by okynos** [wazuh/wazuh-qa#94]
Hello team,

We want to automate our testing components process by adding YAML template that reflects all possible combinations, a briefly introduction could be:
```
# ID of the test template
# Values allowed: An unique integer
id: 1

# Name of the test
# Values allowed: A descriptive name for the test
description: "Add file in realtime."

# Version of the specification template
# Values allowed: ?????
spec_version: "0.1"

# Date of creation of the first file version
# Values allowed: Date
creation_date: 11/02/2019

# Date of the last modification
# Values allowed: Date
modification_date: 11/02/2019

# Name of the provisioner
# Values allowed: vm or docker
provisioner: docker

# Tier of the test. The lower the number, the higher the priority.
# Values allowed: An integer between 0 and 5.
tier: 0

# Category of the tests specified.
# Values allowed: ?????
category: file-integrity-monitoring

# Tags to classify the test
# Values allowed: Any tag
tags: fim, file integrity monitoring, who data, file modification, changes, hash

# Subcategory of the tests specified
# Values allowed: ?????
subcategory: file-integrity-monitoring

# Decides from where Wazuh is installed
# Values allowed: package version or branch
package_source: 

# Targets where the tests will be executed
# Values allowed: agent, manager or all
target: manager

# Specifies whether the cluster should be active.
# Values allowed: enabled or disabled
cluster_mode: enabled

# Targets where the tests will be executed if the cluster is enabled.
# Values allowed: master, worker or both of them
cluster_target: master, worker

# Operative System of the manager
# Values allowed:
#   - centos-7-slave
#   - centos-6-slave
#   - centos-5-slave
#   - debian-stretch-slave
#   - debian-jessie-slave
#   - fedora-29-slave
#   - fedora-28-slave
#   - ubuntu-cosmic-slave
#   - ubuntu-bionic-slave
#   - ubuntu-xenial-slave
manager_os: ubuntu-cosmic-slave

# Operative System of the agent
# Values allowed:
#   - centos-7-slave
#   - centos-6-slave
#   - centos-5-slave
#   - debian-stretch-slave
#   - debian-jessie-slave
#   - fedora-29-slave
#   - fedora-28-slave
#   - ubuntu-cosmic-slave
#   - ubuntu-bionic-slave
#   - ubuntu-xenial-slave
agent_os: centos-7-slave

# Number of agents needed for the tests
# Values allowed: An integer between 0 and ?????
total_agents: 1

# Number of managers needed for the tests
# Values allowed: An integer between 0 and ?????
total_managers: 1

# Wazuh's maximum version of the manager
# Values allowed: Any Wazuh's manager version (format MAJOR.MINOR)
wazuh_max_version_manager: "3.9"

# Wazuh's minimum version of the manager
# Values allowed: Any Wazuh's agent version (format MAJOR.MINOR)
wazuh_min_version_manager: "3.7"

# Specifies whether the manager needs to have installed the API
# Values allowed: yes or no
need_api: no

##########################################################
#                      TEST SECTION                      #
##########################################################

managers:
  - id: 0
    configuration_template : "configuration_template/ossec.conf.manager0"
    arrangements : "arrangements/arrangements.py"
    trigger: "trigger/trigger.py"
    output: "results_checker.py"

agents:
  - id: 0
    configuration_template : "configuration_template/ossec.conf.agent0"
    arrangements : "arrangements/arrangements.py"
    trigger: "trigger/trigger.py"
    output: "results_checker.py"
```

It could change during the develop but, but it's a good point to start.
We have to attach such template to our Jenkins process.

Regards.

**Comment by okynos** [comment]
Hello team,

We have done some advances on template definition to work with Jenkins.
We have done some tests with template Groovy library, but we have seen that Jenkins could parse yaml at the same way that external library so finlly we have decided to remove it.
We have defined different templates to different levels of test:
- Common level, on this level the yaml file defines what possible values we can test, one example is:
```
description: "Information template about available modules and options."
version: "0.1"
available_provisioners:
  - docker
  - vm

available_modules:
  - fim
  - logcollector
  - sca

available_tiers:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5

available_categories:
  - File integrity monitoring
  - System configuracion assessment
  - Log data collector
  - System inventory
  - Intrusion detection system
  - Incident response
  - Cloud provider security
  - Container security

available_tags:
  - fim
  - whodata
  - logcollector
  - syscheck
  - rootcheck
  - sca
  - syscollector
  - ciscat
  - openscap
  - woodle
  - azure
  - amazon
  - db
  - generic

available_targets:
  - manager
  - agent
  - api

available_cluster_mode:
  - enabled
  - disabled

available_cluster_target:
  - master
  - worker

available_systems:
  - centos-7
  - centos-6
  - centos-5
  - redhat-8
  - redhat-7
  - redhat-6
  - oraclelinux-7
  - oraclelinux-6
  - amazonlinux-2
  - fedora-30
  - fedora-29
  - fedora-28
  - fedora-27
  - fedora-26
  - fedora-25
  - fedora-24
  - fedora-23
  - fedora-22
  - debian-buster
  - debian-stretch
  - debian-jessie
  - debian-wheezy
  - ubuntu-disco
  - ubuntu-cosmic
  - ubuntu-bionic
  - ubuntu-artful
  - ubuntu-zesty
  - ubuntu-yakkety
  - ubuntu-xenial
  - ubuntu-wily
  - ubuntu-vivid
  - ubuntu-trusty
  - ubuntu-precise

minimum_supported_version: "3.5.0"
maximum_supported_version: "3.9.3"
```

- Module level, when we are inside of a module folder we will define what tests we can launch, one example (fim module):
```
description: "File integrity monitoring module test suite"
category: File integrity monitoring
tags:
  - fim
available_tests:
  - auto_ignore_test
  - change_file_group
  - change_file_owner
  - change_file_perm
  - files
  - group
  - inode
  - md5_sum
  - nodiff
  - owner
  - perm
  - recursion_level
  - sha1_sum
  - sha256_sum
  - size
  - tags
```

- Test level, finally on test level we define what checks we can do and where we can find it, also the managers and agents that we need and other requirements, one example (files related test):
```
id: 1
description: 'Test of fim alert related with files.'
provisioner: docker
tier: 5
target:
  - manager
  - agent

cluster_mode: disabled

system_target:
  - centos-7
  - debian-buster

available_tests:
  - add
  - delete
  - modify

number_of_agents: 1
number_of_managers: 1
minimum_supported_version: "3.5.0"
maximum_supported_version: "3.9.3"

##########################################################
#                      TEST SECTION                      #
##########################################################

tests:
  - add:
    - managers:
      - 0:
        - configuration_template : "---"
        - arrangements : "manager/arrangements.py"
        - trigger: "manager/trigger.py"
        - output: "manager/results_checker.py"

    - agents:
      - 0:
        - configuration_template : "---"
        - arrangements : "agent/arrangements.py"
        - trigger: "agent/trigger.py"
        - output: "agent/results_checker.py"

  - delete:
    - managers:
      - 0:
        - configuration_template : "---"
        - arrangements : "manager/arrangements.py"
        - trigger: "manager/trigger.py"
        - output: "manager/results_checker.py"

    - agents:
      - 0:
        - configuration_template : "---"
        - arrangements : "agent/arrangements.py"
        - trigger: "agent/trigger.py"
        - output: "agent/results_checker.py"

  - modify:
    - managers:
      - 0:
        - configuration_template : "---"
        - arrangements : "manager/arrangements.py"
        - trigger: "manager/trigger.py"
        - output: "manager/results_checker.py"

    - agents:
      - 0:
        - configuration_template : "---"
        - arrangements : "agent/arrangements.py"
        - trigger: "agent/trigger.py"
        - output: "agent/results_checker.py"
```

These yamls are opened to changes, because our definition still lazy.

**Comment by okynos** [comment]
Hello team,

We have done some changes on test template definition to work even better with Jenkins:
```
id: 1
description: 'Test of fim alert related with files.'
provisioner: docker
tier: 5
target:
  - manager
  - agent

cluster_mode: disabled

system_target:
  - centos-7
  - debian-buster

available_tests:
  - add
  - delete
  - modify

number_of_agents: 1
number_of_managers: 1
minimum_supported_version: '3.5.0'
maximum_supported_version: '3.9.3'

##########################################################
#                      TEST SECTION                      #
##########################################################

tests:
  add:
    managers:
      0:
        configuration_template : "---"
        arrangements : "manager/arrangements.py"
        trigger: "manager/trigger.py"
        output: "manager/results_checker.py"

    agents:
      0:
        configuration_template : "---"
        arrangements : "agent/arrangements.py"
        trigger: "agent/trigger.py"
        output: "agent/results_checker.py"

  delete:
    managers:
      0:
        configuration_template : "---"
        arrangements : "manager/arrangements.py"
        trigger: "manager/trigger.py"
        output: "manager/results_checker.py"

    agents:
      0:
        configuration_template : "---"
        arrangements : "agent/arrangements.py"
        trigger: "agent/trigger.py"
        output: "agent/results_checker.py"

  modify:
    managers:
      0:
        configuration_template : "---"
        arrangements : "manager/arrangements.py"
        trigger: "manager/trigger.py"
        output: "manager/results_checker.py"

    agents:
      0:
        configuration_template : "---"
        arrangements : "agent/arrangements.py"
        trigger: "agent/trigger.py"
        output: "agent/results_checker.py"
```
Now the test part doesn't have dash `-` because each dash generate one array on Jenkins.

We have done some tests reading such template and parsing the parameters, now we can launch instances that match template criteria.

Regards.

**Comment by okynos** [comment]
Hello team,

We have upgraded a little bit the test template (tests array only):
```
##########################################################
#                      TEST SECTION                      #
##########################################################

tests:
  add:
    managers:
      0:
        configuration_template: "---"
        arrangement: "manager/arrangement.py"
#        trigger: "manager/trigger.py"
        output: "manager/checker.py"

    agents:
      0:
        configuration_template : "---"
        arrangement: "agent/arrangement.py"
        trigger: "agent/trigger.py"
        output: "agent/checker.py"

  delete:
    managers:
      0:
        configuration_template: "---"
        arrangement: "manager/arrangement.py"
#        trigger: "manager/trigger.py"
        output: "manager/checker.py"

    agents:
      0:
        configuration_template: "---"
        arrangement: "agent/arrangement.py"
        trigger: "agent/trigger.py"
        output: "agent/checker.py"

  modify:
    managers:
      0:
        configuration_template: "---"
        arrangement: "manager/arrangement.py"
#        trigger: "manager/trigger.py"
        output: "manager/checker.py"

    agents:
      0:
        configuration_template: "---"
        arrangement: "agent/arrangement.py"
        trigger: "agent/trigger.py"
        output: "agent/checker.py"
```
Now `arrangements` is called `arrangement` and sometimes trigger isn't available.

We have also created two playbooks one to transfer tests scripts to docker hosts and other to launch python scripts like `arrangement` or `trigger`.

We have done some initial tests with great results but need more development.

Regards.

**Comment by okynos** [comment]
Hello team,

We have upgraded again the test template (tests array only):
```
##########################################################
#                      TEST SECTION                      #
##########################################################

tests:
  add:
    managers:
      0:
        arrangement: "manager/arrangement.py"
        output: "manager/checker.py"

    agents:
      0:
        arrangement: "agent/arrangement.py"
        trigger: "agent/trigger.py"

  delete:
    managers:
      0:
        arrangement: "manager/arrangement.py"
        output: "manager/checker.py"

    agents:
      0:
        arrangement: "agent/arrangement.py"
        trigger: "agent/trigger.py"

  modify:
    managers:
      0:
        arrangement: "manager/arrangement.py"
        output: "manager/checker.py"

    agents:
      0:
        arrangement: "agent/arrangement.py"
        trigger: "agent/trigger.py"
```
We have removed configuration script due to it isn't needed yet.
We have improved our Jenkins pipeline, now we can launch such scripts for manager and agent.
We have done some tests but need more development.

Regards.
